/* ============================================================================
 * songs.js — дані для розділу «Пісні» (вивчення текстів NEFFEX тощо).
 * Підключається в index.html ПЕРЕД основним скриптом.
 *
 * Структура пісні:
 *   {
 *     id:      "унікальний-slug",      // ключ для статусу вивчення в localStorage
 *     artist:  "NEFFEX",
 *     title:   "Назва",
 *     ytId:    "YouTube video id",     // з https://youtube.com/watch?v=XXXX → "XXXX"
 *     sections: [ { label, lines: [ {en, ua} ] } ],
 *     glossary: { "слово": "переклад" } // hover для слів, яких НЕМАЄ в EN_TO_UA
 *                                       // (ключі — нижній регістр; апострофи можна)
 *     slang: [ {en, ua, note} ]         // ОКРЕМИЙ сленг/вирази (НЕ змішується з WORDS)
 *   }
 *
 * Назви секцій: ВСТУП · КУПЛЕТ 1/2/3 · ПРИСПІВ · ПРЕД-ПРИСПІВ · БРИДЖ · ПРОГРАШ · КІНЦІВКА
 * ========================================================================== */

const SONGS = [
  {
    id: "neffex-baller",
    artist: "NEFFEX",
    title: "Baller 🍾",
    ytId: "42JyRjrLzjY",
    sections: [
      { label: "КУПЛЕТ 1", lines: [
        { en: "Ooh, like Lebron though or like Lonzo",                ua: "У-у, наче Леброн, або як Лонзо" },
        { en: "Ooh, I'm a baller, yeah, shot caller",                 ua: "У-у, я крутій, так, я тут усе вирішую" },
        { en: "Yeah, they love me, you can't touch me",               ua: "Так, мене люблять, мене не дістати" },
        { en: "Nah, can't trust me, I'm too lucky",                   ua: "Не-а, мені не довіряй, я надто везучий" },
        { en: "Look at me, look at you, what you see, what you do",    ua: "Глянь на мене, глянь на себе — що ти бачиш, що ти робиш" },
        { en: "Baby, please, think it through, drink it up, enjoy the view", ua: "Крихітко, прошу, обдумай це, випий до дна, насолоджуйся краєвидом" },
        { en: "MVP, got my crew, Nike on my shoes",                   ua: "Найцінніший гравець, зі мною моя братва, Nike на кросівках" },
        { en: "Might be sippin' booze, slightly feelin' loose",       ua: "Може, потягую випивку, трохи розслабився" },
        { en: "If I want it, then I'll have it",                      ua: "Якщо я цього хочу — я це отримаю" },
        { en: "Got an iced wrist causin' damage",                     ua: "Зап'ястя в діамантах — аж сліпить" },
        { en: "Just like I planned it, I'll be damn rich",            ua: "Точно як і планував — буду до біса багатий" },
        { en: "Have a chef in the back, make a sandwich",             ua: "Маю кухаря там позаду — хай зробить сендвіч" },
        { en: "Ooh, she got it all, all, I just want it all, all",    ua: "У-у, у неї є все-все, а я просто хочу все-все" },
        { en: "Baby, we could ba-all, you just gotta fa-all",         ua: "Крихітко, ми могли б відриватися, тобі лиш треба піддатися" },
        { en: "I could be your ma-an, payin' for your ta-an",         ua: "Я міг би бути твоїм чоловіком, платити за твою засмагу" },
        { en: "I'm your biggest fa-an, you said this your ja-am, yeah (Yeah)", ua: "Я твій найбільший фанат, ти сказала — це твій улюблений трек, так (Так)" }
      ]},
      { label: "ПРИСПІВ", lines: [
        { en: "Oh, yeah, I'm livin' up life, like a baller (Baller)", ua: "О так, я живу на повну, як крутій (Крутій)" },
        { en: "I'm livin' like white, like I'm Walter (Like I'm Walter)", ua: "Живу шикарно, наче я Волтер (Наче я Волтер)" },
        { en: "She always call me, I never call her (Never call her)", ua: "Вона завжди дзвонить мені, я їй — ніколи (Ніколи їй)" },
        { en: "Oh, yeah, I'm livin' this life like a baller (Baller)", ua: "О так, я живу це життя як крутій (Крутій)" }
      ]},
      { label: "КУПЛЕТ 2", lines: [
        { en: "I pull up in a coup up in a Chevy",                    ua: "Під'їжджаю на купе, на Chevy" },
        { en: "I'ma hit it in the back, if she let me",               ua: "Зроблю своє на задньому сидінні, якщо вона дозволить" },
        { en: "And take your time, baby, gettin' ready",              ua: "І не поспішай, крихітко, збирайся" },
        { en: "I want you lookin' fine, oh, lookin' sexy, yeah, yeah", ua: "Хочу, щоб ти мала чудовий вигляд, о, сексуальний, так, так" },
        { en: "I be, I be, I be, I be, I be turnin' up",              ua: "Я відриваюсь, відриваюсь, відриваюсь" },
        { en: "Got no ID, ID, ID, ID, but she cute as fuck",          ua: "Без документів, але вона до біса мила" },
        { en: "So, I told her, she could kick it, but I said she couldn't touch", ua: "Тож я сказав, що вона може зависнути, але торкатися — зась" },
        { en: "Now, all she, all she, all she wants to do is kiss and hug", ua: "А тепер усе, чого вона хоче — цілуватись і обійматись" },
        { en: "I could go all day, I'ma do my thing",                 ua: "Я можу хоч цілий день, робитиму своє" },
        { en: "I'ma stay ballin', like it's my driveway",             ua: "Лишатимусь на коні, наче це моя під'їзна доріжка" },
        { en: "I'ma go all-in, party like Friday",                    ua: "Піду ва-банк, гулятиму як у п'ятницю" },
        { en: "I'ma take this day, turn it to my day",                ua: "Візьму цей день і зроблю його своїм" },
        { en: "Ooh, ooh, she love me, sippin' bubbly",                ua: "У-у, вона любить мене, попиваючи шампанське" },
        { en: "Champagne, cocaine, kiss and hug me",                  ua: "Шампанське, кокаїн, цілуй і обіймай мене" },
        { en: "It ain't nothin', droppin' money",                     ua: "Це дрібниці — смітити грошима" },
        { en: "Okay, all day, gettin' lucky, yeah (Yeah)",            ua: "Окей, цілий день щастить, так (Так)" }
      ]},
      { label: "ПРИСПІВ", lines: [
        { en: "Oh, yeah, I'm livin' up life, like a baller (Baller)", ua: "О так, я живу на повну, як крутій (Крутій)" },
        { en: "I'm livin' like white, like I'm Walter (Like I'm Walter)", ua: "Живу шикарно, наче я Волтер (Наче я Волтер)" },
        { en: "She always call me, I never call her (Never call her)", ua: "Вона завжди дзвонить мені, я їй — ніколи (Ніколи їй)" },
        { en: "Oh, yeah, I'm livin' this life like a baller (Baller)", ua: "О так, я живу це життя як крутій (Крутій)" }
      ]},
      { label: "КУПЛЕТ 3", lines: [
        { en: "Yeah, you can catch me in the studio",                 ua: "Так, можеш застати мене в студії" },
        { en: "Yeah, and you'll hear me on the radio",                ua: "Так, і почуєш мене по радіо" },
        { en: "Yeah, you'll hear me through your stereo",             ua: "Так, почуєш мене зі своєї стереосистеми" },
        { en: "Yeah, while I'm lookin' for my cameo",                 ua: "Так, поки я шукаю своє камео" },
        { en: "Yeah, she's textin' me, ooh, wanna get at me, ooh",    ua: "Так, вона пише мені, у-у, хоче підкотити, у-у" },
        { en: "Now she's sextin' me, yeah, she's testin' me",         ua: "Тепер шле мені пікантні повідомлення, так, випробовує мене" },
        { en: "I just let it be, yeah, I'm a vet, you see",           ua: "Я просто пускаю на самоплив, так, я бувалий, розумієш" },
        { en: "Since I was seventeen, welcome to the team, ooh, ooh", ua: "Ще з сімнадцяти, ласкаво просимо в команду, у-у" },
        { en: "Yeah, I deal in bulk, like I'm Costco",                ua: "Так, торгую оптом, наче я Costco" },
        { en: "Yeah, I got this shit on lock, though",                ua: "Так, я все тримаю під контролем" },
        { en: "Yeah, invest my money in my stock, oh",               ua: "Так, вкладаю гроші у свої акції, о" },
        { en: "Yeah, so, I'm growin' round the clock, yo",           ua: "Так, тож я росту цілодобово, йо" },
        { en: "Oh, she like that, wanna try that",                   ua: "О, їй таке подобається, хоче спробувати" },
        { en: "Wanna bite that, she got a nice ass",                 ua: "Хоче вкусити, у неї гарна дупа" },
        { en: "Tr-treat her right, yeah, she sippin' white, yeah",   ua: "Стався до неї добре, так, вона попиває біле, так" },
        { en: "We go all night, 'til we see the sunlight, yeah (Yeah)", ua: "Гуляємо всю ніч, поки не побачимо світанок, так (Так)" }
      ]},
      { label: "ПРИСПІВ", lines: [
        { en: "Oh, yeah, I'm livin' up life, like a baller (Baller)", ua: "О так, я живу на повну, як крутій (Крутій)" },
        { en: "I'm livin' like white, like I'm Walter (Like I'm Walter)", ua: "Живу шикарно, наче я Волтер (Наче я Волтер)" },
        { en: "She always call me, I never call her (Never call her)", ua: "Вона завжди дзвонить мені, я їй — ніколи (Ніколи їй)" },
        { en: "Oh, yeah, I'm livin' this life like a baller (Baller)", ua: "О так, я живу це життя як крутій (Крутій)" }
      ]}
    ],
    // hover-переклади слів (контекстні для цієї пісні; доповнюють основний словник)
    glossary: {
      "ooh": "у-у (вигук)", "nah": "не-а (ні)", "yo": "йо (вигук)",
      "lebron": "Леброн (Джеймс — баскетболіст)", "lonzo": "Лонзо (Болл — баскетболіст; гра слів з «ball»)",
      "baller": "крутій, успішний багатій", "shot": "постріл (тут: shot caller — головний)",
      "caller": "той, хто командує", "touch": "торкатися", "trust": "довіряти",
      "lucky": "везучий", "view": "краєвид, вид", "through": "крізь, наскрізь",
      "mvp": "найцінніший гравець (Most Valuable Player)", "crew": "команда, братва",
      "nike": "Nike (бренд)", "shoes": "взуття, кросівки", "might": "можливо, може",
      "sippin'": "потягую (sip — пити маленькими ковтками)", "booze": "випивка, алкоголь",
      "slightly": "трохи, злегка", "feelin'": "відчуваю", "loose": "розкутий, розслаблений",
      "iced": "у діамантах, в брильянтах", "wrist": "зап'ястя", "causin'": "спричиняє",
      "damage": "шкода (тут: «б'є наповал»)", "planned": "запланував", "damn": "до біса (підсилення)",
      "rich": "багатий", "chef": "шеф-кухар", "sandwich": "сендвіч", "gotta": "мусиш (got to)",
      "ball": "відриватися, розкошувати", "fall": "впасти; закохатися", "payin'": "плачу",
      "tan": "засмага", "biggest": "найбільший", "jam": "улюблений трек",
      "livin'": "живу", "walter": "Волтер (відсилання до Walter White, «Breaking Bad»)",
      "pull": "під'їжджати (pull up)", "coup": "купе (авто, coupe)", "chevy": "Chevy (Chevrolet)",
      "hit": "вдарити; тут «hit it» — переспати (натяк)", "gettin'": "стаю; gettin' ready — збираюсь",
      "ready": "готовий", "fine": "чудовий (вигляд)", "sexy": "сексуальний",
      "turnin'": "відриваюсь (turn up — тусити)", "cute": "милий, симпатичний",
      "kick": "копати; kick it — зависати, тусити", "kiss": "цілувати", "hug": "обіймати",
      "driveway": "під'їзна доріжка", "ballin'": "розкошую, живу красиво",
      "all-in": "ва-банк, поставити все", "party": "вечірка; гуляти",
      "bubbly": "шампанське (розм.)", "champagne": "шампанське", "cocaine": "кокаїн",
      "ain't": "не / немає (розм.)", "nothin'": "нічого, дрібниця", "droppin'": "смітити (грошима)",
      "studio": "студія", "radio": "радіо", "stereo": "стереосистема", "cameo": "камео, епізодична поява",
      "textin'": "пише повідомлення", "sextin'": "шле інтимні повідомлення (sexting)",
      "testin'": "випробовує", "vet": "бувалий, досвідчений (від veteran)",
      "seventeen": "сімнадцять", "team": "команда", "deal": "мати справу; торгувати",
      "bulk": "опт, великими партіями", "costco": "Costco (мережа гуртових магазинів)",
      "shit": "лайно (тут: «все це»)", "lock": "замок; on lock — під контролем",
      "invest": "вкладати, інвестувати", "stock": "акції", "growin'": "росту",
      "clock": "годинник; round the clock — цілодобово", "bite": "кусати",
      "ass": "дупа (груб.)", "treat": "ставитися; пригощати", "sunlight": "сонячне світло, світанок",
      "i'ma": "я зараз / я буду (I'm gonna)"
    },
    slang: [
      { en: "baller",          ua: "крутій, багатій",       note: "той, хто «грає по-крупному»; від баскетболу → успішна заможна людина" },
      { en: "shot caller",     ua: "головний, бос",          note: "той, хто приймає рішення і всім керує" },
      { en: "iced",            ua: "в діамантах",            note: "ice = діаманти; iced wrist — зап'ястя у брильянтах" },
      { en: "causin' damage",  ua: "б'є наповал",            note: "букв. «завдає шкоди» → справляє сильне враження" },
      { en: "ball / ballin'",  ua: "розкошувати",            note: "жити красиво, купатися в розкошах" },
      { en: "this your jam",   ua: "це твій улюблений трек", note: "jam — улюблена пісня" },
      { en: "livin' up life",  ua: "жити на повну",          note: "проживати життя на максимум" },
      { en: "like I'm Walter", ua: "як Волтер Вайт",         note: "відсилання до Walter White («Breaking Bad»); гра слів з «white» — і розкіш, і натяк" },
      { en: "hit it",          ua: "переспати",              note: "натяк (груб.-розм.)" },
      { en: "turn up",         ua: "відриватися",            note: "веселитися на повну, тусити" },
      { en: "kick it",         ua: "зависати",               note: "проводити час, тусити (без зобов'язань)" },
      { en: "as fuck",         ua: "до біса (груб.)",        note: "підсилювач: «cute as fuck» — неймовірно мила" },
      { en: "do my thing",     ua: "робити своє",            note: "займатися своєю справою, бути собою" },
      { en: "all-in",          ua: "ва-банк",                note: "поставити все, видатися повністю (з покеру)" },
      { en: "bubbly",          ua: "шампанське",             note: "розмовна назва шампанського (через бульбашки)" },
      { en: "droppin' money",  ua: "смітити грошима",        note: "багато й легко витрачати" },
      { en: "gettin' lucky",   ua: "щастить / переспати",    note: "подвійний сенс: і «везе», і інтимний натяк" },
      { en: "get at me",       ua: "підкотити",              note: "звертатися/залицятися, «дістатися» до когось" },
      { en: "sexting",         ua: "секстинг",               note: "обмін інтимними повідомленнями" },
      { en: "vet",             ua: "бувалий",                note: "досвідчений, «ветеран» своєї справи" },
      { en: "deal in bulk",    ua: "торгувати оптом",        note: "продавати великими партіями; гра слів з «deal» — оборудка" },
      { en: "on lock",         ua: "під контролем",          note: "повністю під контролем, «схоплено»" },
      { en: "round the clock", ua: "цілодобово",             note: "24/7, без перерви" },
      { en: "sippin' white",   ua: "попиває біле (вино)",    note: "ймовірно біле вино; можливий подвійний сенс" },
      { en: "coup",            ua: "купе",                   note: "від «coupe» — двомісне авто" },
      { en: "booze",           ua: "випивка",                note: "алкоголь (розм.)" }
    ]
  }
  ,
  {
    id: "neffex-lit",
    artist: "NEFFEX",
    title: "Lit 🔥",
    ytId: "AHhiRc0Lnq4",
    sections: [
      { label: "КУПЛЕТ 1", lines: [
        { en: "I'm just fuckin' lit, man, I'm just fuckin' lit",              ua: "Я просто до біса бухий, чуваку, просто бухий" },
        { en: "Drank a bottle of this shit, man, bottle of this shit",         ua: "Ковтнув пляшку цього добра, чуваку, пляшку" },
        { en: "I'm about to write a hit, man, about to write a hit",           ua: "Зараз напишу хіт, чуваку, напишу хіт" },
        { en: "No, I'm never gonna quit, man, never gonna quit",               ua: "Ні, я ніколи не здамся, чуваку, ніколи" },
        { en: "I just took another hit, man, took another hit",                ua: "Щойно ще разок затягнувся, чуваку, ще разок" },
        { en: "I'm about to lose my shit, man, about to lose my shit",         ua: "Зараз зірвусь, чуваку, зірвусь" },
        { en: "Does she have a fuckin' wristband? Yeah, she needs that shit",  ua: "У неї є браслет? Так, їй він потрібен" },
        { en: "Better get her out real quick, man, get her out real quick (Quick)", ua: "Краще виводь її звідси швидко, чуваку, швидко (Швидко)" }
      ]},
      { label: "ПРИСПІВ", lines: [
        { en: "Are you the present or the future? (Present or the future)",    ua: "Ти теперішнє чи майбутнє? (Теперішнє чи майбутнє)" },
        { en: "Are you a drinker or a boozer? (Drinker or a boozer)",          ua: "Ти п'єш по-людськи чи бухаєш? (П'єш чи бухаєш)" },
        { en: "Are you a giver or a user? (Giver or a user)",                  ua: "Ти даєш чи тільки береш? (Даєш чи береш)" },
        { en: "Are you a winner or a loser? (Winner or a loser)",              ua: "Ти переможець чи невдаха? (Переможець чи невдаха)" },
        { en: "Yeah, and I said that I would never back down",                 ua: "Так, і я казав, що ніколи не здамся" },
        { en: "And I said that I would never back down",                       ua: "І казав, що ніколи не здамся" },
        { en: "And I said that I would never back down",                       ua: "І казав, що ніколи не здамся" },
        { en: "I swore that I would never fuckin' back down",                  ua: "Клявся, що ніколи до біса не здамся" }
      ]},
      { label: "КУПЛЕТ 2", lines: [
        { en: "Pass the bottle and the fifth, man, bottle and the fifth",      ua: "Передай пляшку і п'ятак, чуваку, пляшку і п'ятак" },
        { en: "'Cause I'm feeling like the shit, man, feeling like the shit",  ua: "Бо я відчуваю себе вершиною, чуваку, вершиною" },
        { en: "Yeah, her body's like a gift, man, body's like a gift",         ua: "Так, її тіло — наче подарунок, чуваку, подарунок" },
        { en: "'Cause she's looking hella fit, man, looking hella fit",        ua: "Бо вона до біса у формі, чуваку, у формі" },
        { en: "And I can't always commit, man, can't always commit",           ua: "І я не завжди можу зобов'язуватись, чуваку" },
        { en: "Pull a trigger on this shit, man, trigger on this shit",        ua: "Вирішуюсь на це, чуваку, вирішуюсь" },
        { en: "'Cause I feel I haven't lived, man, feel I haven't lived",      ua: "Бо відчуваю, що не жив по-справжньому, чуваку" },
        { en: "'Til I got nothing to miss, man, got nothing to miss (Miss)",   ua: "Поки мені нема чого більше втрачати, чуваку (Втрачати)" }
      ]},
      { label: "ПРИСПІВ", lines: [
        { en: "Are you the present or the future? (Present or the future)",    ua: "Ти теперішнє чи майбутнє? (Теперішнє чи майбутнє)" },
        { en: "Are you a drinker or a boozer? (Drinker or a boozer)",          ua: "Ти п'єш по-людськи чи бухаєш? (П'єш чи бухаєш)" },
        { en: "Are you a giver or a user? (Giver or a user)",                  ua: "Ти даєш чи тільки береш? (Даєш чи береш)" },
        { en: "Are you a winner or a loser? (Winner or a loser)",              ua: "Ти переможець чи невдаха? (Переможець чи невдаха)" },
        { en: "Yeah, and I said that I would never back down",                 ua: "Так, і я казав, що ніколи не здамся" },
        { en: "And I said that I would never back down",                       ua: "І казав, що ніколи не здамся" },
        { en: "And I said that I would never back down",                       ua: "І казав, що ніколи не здамся" },
        { en: "I swore that I would never fuckin' back down",                  ua: "Клявся, що ніколи до біса не здамся" }
      ]}
    ],
    glossary: {
      "lit":       "бухий, п'яний (під кайфом)",
      "fuckin'":   "до біса (підсилення, груб.)",
      "man":       "чуваку (звернення)",
      "drank":     "випив (від drink)",
      "gonna":     "збираюся (going to)",
      "never":     "ніколи",
      "quit":      "здаватися, кидати",
      "took":      "взяв (від take)",
      "hit":       "хіт (пісня); тут: затягнутися",
      "lose":      "втрачати, зривати",
      "shit":      "лайно; тут: «добро», підсилення (груб.)",
      "wristband": "браслет (клубний — допуск на вечірку)",
      "real":      "справжній; real quick = дуже швидко",
      "quick":     "швидкий, швидко",
      "future":    "майбутнє",
      "drinker":   "той, хто п'є (помірно)",
      "boozer":    "п'яниця, бухар",
      "giver":     "той, хто дає",
      "user":      "той, хто бере/використовує (тут: споживач)",
      "winner":    "переможець",
      "loser":     "невдаха",
      "back":      "назад; back down — відступати",
      "down":      "вниз; back down — здаватися",
      "swore":     "клявся (від swear)",
      "swear":     "клястися",
      "'til":      "поки не (until)",
      "'cause":    "бо, тому що (because)",
      "pass":      "передати, подати",
      "fifth":     "п'ятак (750 мл пляшка — п'ята частина галона)",
      "feeling":   "відчуваю, відчуття",
      "body":      "тіло",
      "hella":     "дуже, до біса (каліфорнійський сленг)",
      "fit":       "у формі, підтягнутий/а",
      "gift":      "подарунок",
      "commit":    "зобов'язуватися (у стосунках)",
      "pull":      "тягнути; pull a trigger — натиснути на гашок",
      "trigger":   "курок, гашок; тут: вирішитися",
      "lived":     "жив (від live)",
      "nothing":   "нічого"
    },
    slang: [
      { en: "lit",                   ua: "бухий, п'яний",             note: "тут: п'яний/під кайфом (від алкоголю); ширше сленгове значення — «класний, у вогні»" },
      { en: "take a hit",            ua: "затягнутися",               note: "зробити затяжку (наркотичний натяк)" },
      { en: "lose my shit",          ua: "зірватися, збожеволіти",    note: "втратити контроль, вийти з себе" },
      { en: "wristband",             ua: "клубний браслет",           note: "браслет допуску на вечірку; без нього — виходь" },
      { en: "feeling like the shit", ua: "відчуваю себе вершиною",    note: "«the shit» (з артиклем) = найкращий, бог; без артикля — образа" },
      { en: "hella",                 ua: "дуже, до біса",             note: "каліфорнійський сленг-підсилювач (hella fit = неймовірно у формі)" },
      { en: "the fifth",             ua: "п'ятак (750 мл)",           note: "п'ята частина галона — стандартна пляшка міцного (США)" },
      { en: "commit",                ua: "зобов'язуватися",           note: "тут: у стосунках — «бути серйозним»" },
      { en: "pull a trigger",        ua: "натиснути на гашок",        note: "тут метафора: вирішитися на щось, зробити крок" },
      { en: "back down",             ua: "відступати, здаватися",     note: "back down = відмовлятися від позиції під тиском" },
      { en: "nothing to miss",       ua: "нема чого втрачати",        note: "коли вже все пережив — нема чого боятися" },
      { en: "boozer",                ua: "п'яниця, бухар",            note: "гірше ніж drinker: важкий алкоголік" },
      { en: "drinker vs boozer",     ua: "п'єш чи бухаєш",           note: "приспів ставить риторичні пари: даєш/береш, перемагаєш/програєш" },
      { en: "giver vs user",         ua: "даєш чи тільки береш",      note: "класичне протиставлення: той хто вкладає vs хто лише отримує" }
    ]
  }
  ,
  {
    id: "neffex-badass",
    artist: "NEFFEX",
    title: "Badass 💋",
    ytId: "rzElZuhGTpU",
    sections: [
      { label: "КУПЛЕТ 1", lines: [
        { en: "The wind is blowin' through her hair (Blowin' through her hair)", ua: "Вітер розвіває її волосся (Розвіває волосся)" },
        { en: "We like to head out on the road (Head out on the road)",          ua: "Ми любимо вирушати в дорогу (Вирушати в дорогу)" },
        { en: "And you know we don't really care (We don't really care)",        ua: "І знаєш, нам, по суті, байдуже (Нам байдуже)" },
        { en: "'Cause we're just doin' what we want (We're just doin' what we want)", ua: "Бо ми просто робимо, що хочемо (Робимо, що хочемо)" },
        { en: "She likes it when I treat her good (She likes it when I treat her good)", ua: "Їй подобається, коли я ставлюся до неї добре (коли ставлюся добре)" },
        { en: "She likes it when I treat her bad (She likes it when I treat her bad)",  ua: "Їй подобається, коли я ставлюся до неї погано (коли ставлюся погано)" },
        { en: "She likes to travel all around (That's right)",                   ua: "Вона любить мандрувати всюди (Саме так)" },
        { en: "I take her everywhere and back (Let's go, yeah)",                 ua: "Я вожу її скрізь і назад (Погнали, так)" },
        { en: "Oh, you fuckin' with the man, girl",                             ua: "О, ти зв'язалася зі справжнім мужиком, дівчино" },
        { en: "You throw it right back, know I like that, I'ma bite back",       ua: "Ти даєш відсіч, знаєш, мені таке до вподоби, і я кусну у відповідь" },
        { en: "You know, I've become a fan girl, the way you throwback",         ua: "Знаєш, я став твоїм фанатом — те, як ти все повертаєш у ретро-стилі" },
        { en: "Like a Kodak, girl, you own that",                               ua: "Наче кадр Kodak, дівчино, тобі це личить" },
        { en: "Cruise around with out a plan, girl",                            ua: "Катаємось без жодного плану, дівчино" },
        { en: "We'll never go back, girl, you know that you are so bad",         ua: "Ми ніколи не повернемось, дівчино, ти ж знаєш, яка ти відчайдушна" },
        { en: "Let's just spend a couple grand, girl",                          ua: "Давай просто спустимо пару тисяч, дівчино" },
        { en: "You know fuckin' with the man, girl (Man, girl, man, girl)",      ua: "Знаєш, ти зв'язалася зі справжнім мужиком, дівчино (Мужиком, дівчино)" }
      ]},
      { label: "ПРЕД-ПРИСПІВ", lines: [
        { en: "Yeah, oh, you could've been a good girl (Good girl)",             ua: "Так, о, ти могла б бути хорошою дівчинкою (Хорошою)" },
        { en: "But instead, you chose the real world (Real world)",              ua: "Але натомість ти обрала справжнє життя (Справжнє життя)" },
        { en: "Yeah, you've always been a savage (Savage)",                      ua: "Так, ти завжди була відчайдушною (Відчайдушна)" },
        { en: "Oh, you've always been a bad chick (Bad chick)",                  ua: "О, ти завжди була крутою дівкою (Крута дівка)" },
        { en: "I don't care if you got issues, daddy left, but I'm with you",    ua: "Мені байдуже, що в тебе проблеми, тато пішов — але я з тобою" },
        { en: "So, come with me never look back, we're livin' life like a badass", ua: "Тож ходи зі мною, не озирайся — ми живемо як справжні бунтарі" }
      ]},
      { label: "ПРИСПІВ", lines: [
        { en: "Yeah, oh, you could've been a good girl (Good girl)",             ua: "Так, о, ти могла б бути хорошою дівчинкою (Хорошою)" },
        { en: "But instead, you chose the real world (Real world)",              ua: "Але натомість ти обрала справжнє життя (Справжнє життя)" },
        { en: "Yeah, you've always been a savage (Savage)",                      ua: "Так, ти завжди була відчайдушною (Відчайдушна)" },
        { en: "Oh, you've always been a bad chick (Bad chick)",                  ua: "О, ти завжди була крутою дівкою (Крута дівка)" },
        { en: "I don't care if you got issues, daddy left, but I'm with you",    ua: "Мені байдуже, що в тебе проблеми, тато пішов — але я з тобою" },
        { en: "So, come with me never look back, we're livin' life like a badass", ua: "Тож ходи зі мною, не озирайся — ми живемо як справжні бунтарі" }
      ]},
      { label: "КУПЛЕТ 2", lines: [
        { en: "Yeah, cruisin' PCH with the top down",                           ua: "Так, мчимо по Тихоокеанському шосе з опущеним дахом" },
        { en: "Drop down, headed no where fast never stop now, not now",        ua: "Газу — і мчимо в нікуди, не зупиняємось, тільки не зараз" },
        { en: "We ain't slowin' down, never knowin' now",                       ua: "Ми не сповільнюємось, наперед нічого не знаємо" },
        { en: "We're just headin' south what it's all about",                   ua: "Просто прямуємо на південь — ось у чому вся суть" },
        { en: "Never had a doubt, yeah, she be sittin' shotgun",                ua: "Жодного сумніву, так, вона сидить поруч на передньому" },
        { en: "She a hot one, in the hot sun, crop top on, I'ma hop on",        ua: "Вона гаряча штучка, під палючим сонцем, у топику — я застрибую" },
        { en: "Every single day, head a different way",                         ua: "Щодня прямуємо в новий бік" },
        { en: "Never stay in place, don't care what they say",                  ua: "Ніколи не сидимо на місці, начхати, що кажуть" },
        { en: "We gon' do it anyway, always by my side",                        ua: "Ми все одно це зробимо, ти завжди поруч" },
        { en: "Oh, we're livin' life right, every night we just drive by",      ua: "О, ми живемо правильно, щоночі просто мчимо повз" },
        { en: "Cruisin' high life, we're alive, not just gettin' by",           ua: "Купаємось у розкошах, ми живі, а не просто животіємо" },
        { en: "Not just lettin' life pass right underneath our sight",          ua: "Не просто дивимось, як життя спливає в нас перед очима" },
        { en: "Grab it real tight, okay, every day is a new day",               ua: "Хапай його міцно, гаразд, кожен день — новий день" },
        { en: "In a new place, rent a new space, see a new face",               ua: "У новому місці, орендуємо нову хату, бачимо нове обличчя" },
        { en: "In a few days, move a new way to a new state",                   ua: "За кілька днів рушаємо по-новому в новий штат" },
        { en: "That's great, rent an estate for our next date, haha",           ua: "Це круто — орендуємо маєток для наступного побачення, ха-ха" }
      ]},
      { label: "ПРЕД-ПРИСПІВ", lines: [
        { en: "Yeah, oh, you could've been a good girl (Good girl)",             ua: "Так, о, ти могла б бути хорошою дівчинкою (Хорошою)" },
        { en: "But instead, you chose the real world (Real world)",              ua: "Але натомість ти обрала справжнє життя (Справжнє життя)" },
        { en: "Yeah, you've always been a savage (Savage)",                      ua: "Так, ти завжди була відчайдушною (Відчайдушна)" },
        { en: "Oh, you've always been a bad chick (Bad chick)",                  ua: "О, ти завжди була крутою дівкою (Крута дівка)" },
        { en: "I don't care if you got issues, daddy left, but I'm with you",    ua: "Мені байдуже, що в тебе проблеми, тато пішов — але я з тобою" },
        { en: "So, come with me never look back, we're livin' life like a badass", ua: "Тож ходи зі мною, не озирайся — ми живемо як справжні бунтарі" }
      ]},
      { label: "ПРИСПІВ", lines: [
        { en: "Yeah, oh, you could've been a good girl (Good girl)",             ua: "Так, о, ти могла б бути хорошою дівчинкою (Хорошою)" },
        { en: "But instead, you chose the real world (Real world)",              ua: "Але натомість ти обрала справжнє життя (Справжнє життя)" },
        { en: "Yeah, you've always been a savage (Savage)",                      ua: "Так, ти завжди була відчайдушною (Відчайдушна)" },
        { en: "Oh, you've always been a bad chick (Bad chick)",                  ua: "О, ти завжди була крутою дівкою (Крута дівка)" },
        { en: "I don't care if you got issues, daddy left, but I'm with you",    ua: "Мені байдуже, що в тебе проблеми, тато пішов — але я з тобою" },
        { en: "So, come with me never look back, we're livin' life like a badass", ua: "Тож ходи зі мною, не озирайся — ми живемо як справжні бунтарі" }
      ]}
    ],
    glossary: {
      "wind": "вітер", "blowin'": "дме, розвіває", "hair": "волосся",
      "head": "прямувати, рушати (head out — вирушати)", "road": "дорога",
      "really": "справді, по-справжньому", "care": "перейматися; don't care — байдуже",
      "doin'": "робимо", "treat": "ставитися (до когось)", "travel": "подорожувати, мандрувати",
      "everywhere": "скрізь, всюди", "fuckin'": "(груб. підсилення); fuckin' with — зв'язатися з",
      "man": "тут: справжній мужик, крутий", "throw": "кидати; throw it back — давати відсіч",
      "bite": "кусати; bite back — кусати/огризатися у відповідь",
      "fan": "фанат", "throwback": "ретро, повернення в минуле",
      "kodak": "Kodak (фотобренд; «кадр як на фото»)", "own": "володіти; you own that — тобі це личить",
      "cruise": "кататися, їхати без поспіху", "plan": "план",
      "couple": "пара, декілька", "grand": "тисяча доларів (сленг)",
      "could've": "міг/могла б (could have)", "instead": "натомість, замість",
      "chose": "обрав/обрала (від choose)", "real": "справжній, реальний",
      "world": "світ", "savage": "відчайдух; дикий, безбашений",
      "chick": "дівка, чувіха (розм.)", "issues": "проблеми (тут: внутрішні/у житті)",
      "daddy": "тато, татко", "left": "пішов, покинув (від leave)",
      "badass": "крутий бунтар, відчайдух", "cruisin'": "катаємось",
      "pch": "Тихоокеанське шосе (Pacific Coast Highway, Каліфорнія)",
      "top": "тут: дах авто (top down — з опущеним дахом)", "drop": "опускати; drop down — газонути/просісти",
      "headed": "прямую(ємо)", "nowhere": "нікуди", "stop": "зупинятися",
      "ain't": "не / немає (розм.)", "slowin'": "сповільнюємось", "knowin'": "знаючи",
      "headin'": "прямуємо", "south": "південь", "doubt": "сумнів",
      "shotgun": "переднє пасажирське сидіння (ride shotgun)", "hot": "гарячий; тут: сексуальна",
      "sun": "сонце", "crop": "укорочений (crop top — короткий топ)",
      "hop": "стрибати; hop on — застрибнути", "single": "кожен; every single day — буквально щодня",
      "different": "інший, різний", "place": "місце", "side": "бік; by my side — поруч зі мною",
      "right": "правильно; тут: як слід", "night": "ніч", "drive": "їхати; drive by — проїжджати повз",
      "high": "високий; high life — розкішне життя", "alive": "живий",
      "gettin'": "тут: gettin' by — ледь зводити кінці", "lettin'": "дозволяючи",
      "pass": "минати, спливати", "underneath": "під, попід", "sight": "погляд, поле зору",
      "grab": "хапати", "tight": "міцно, туго", "rent": "орендувати",
      "space": "простір; тут: житло, хата", "face": "обличчя", "state": "штат",
      "great": "чудово, круто", "estate": "маєток, садиба", "date": "побачення",
      "gon'": "збираємось (gonna / going to)", "anyway": "все одно, попри все"
    },
    slang: [
      { en: "badass",            ua: "крутий бунтар, відчайдух",   note: "сильна, безстрашна людина, що живе по-своєму (часто схвально)" },
      { en: "fuckin' with",      ua: "зв'язатися, мати справу",    note: "тут: «ти зв'язалася зі справжнім мужиком» (груб.-розм.)" },
      { en: "the man",           ua: "крутий мужик / головний",    note: "впевнений, авторитетний чоловік («він тут головний»)" },
      { en: "throw it back",     ua: "давати відсіч",              note: "відповідати тим самим, не пасувати" },
      { en: "bite back",         ua: "огризатися у відповідь",     note: "відповідати на випад так само різко" },
      { en: "you own that",      ua: "тобі це личить / це твоє",   note: "«own» тут = робити щось упевнено, на всі сто" },
      { en: "Kodak",             ua: "кадр як на фото",            note: "«Kodak moment» — ідеальна мить, варта знімка" },
      { en: "a couple grand",    ua: "пара тисяч (доларів)",       note: "grand = $1000 (сленг)" },
      { en: "savage",            ua: "відчайдух, безбашений",      note: "хтось зухвалий і безстрашний (схвально в сленгу)" },
      { en: "bad chick",         ua: "крута/відчайдушна дівка",    note: "тут «bad» = позитивне: ефектна, зухвала" },
      { en: "got issues",        ua: "мати проблеми",              note: "психологічні травми чи складнощі в житті" },
      { en: "the real world",    ua: "справжнє життя",             note: "життя без прикрас, на противагу «правильному»/тепличному" },
      { en: "ride shotgun",      ua: "сидіти на передньому",       note: "shotgun — переднє пасажирське сидіння поряд з водієм" },
      { en: "top down",          ua: "з опущеним дахом",           note: "про кабріолет — їхати з відкритим верхом" },
      { en: "PCH",               ua: "Тихоокеанське шосе",         note: "Pacific Coast Highway — мальовнича траса вздовж узбережжя Каліфорнії" },
      { en: "crop top",          ua: "укорочений топ",             note: "коротка майка, що відкриває живіт" },
      { en: "hop on",            ua: "застрибнути",                note: "швидко приєднатися/сісти" },
      { en: "high life",         ua: "розкішне життя",             note: "життя на широку ногу, в розкошах" },
      { en: "gettin' by",        ua: "ледь зводити кінці",         note: "виживати, абияк перебиватися (тут — те, чого вони НЕ роблять)" },
      { en: "hella",             ua: "дуже, до біса",              note: "(якщо трапиться) каліфорнійський сленг-підсилювач" }
    ]
  }
  ,
  {
    id: "neffex-new-beginnings",
    artist: "NEFFEX",
    title: "New Beginnings",
    ytId: "f4hcOJAXGxI",
    sections: [
      { label: "КУПЛЕТ 1", lines: [
        { en: "(Damn you look good tonight)",                                ua: "(Чорт, ти сьогодні чудово виглядаєш)" },
        { en: "I needed something",                                          ua: "Мені дечого бракувало" },
        { en: "Someone to trust in, yeah",                                   ua: "Когось, кому можна довіряти, так" },
        { en: "I needed something",                                          ua: "Мені дечого бракувало" },
        { en: "To get me through this life",                                 ua: "Чогось, щоб пройти крізь це життя" },
        { en: "Never saw you coming",                                        ua: "Не чекав на твою появу" },
        { en: "And now we're just running, yeah",                           ua: "А тепер ми просто мчимо, так" },
        { en: "You make me feel nothing",                                    ua: "Поруч із тобою зникають усі тривоги" },
        { en: "When we're driving through the night",                       ua: "Коли ми мчимо крізь ніч" },
        { en: "And I've been looking all around at the places",             ua: "І я роздивлявся навколо всі ці місця" },
        { en: "You and I were seeing so many different faces",              ua: "Ми з тобою бачили стільки різних облич" },
        { en: "We're just cruising right on through this life with a playlist", ua: "Ми просто катаємось крізь це життя під плейлист" },
        { en: "And everything is right",                                    ua: "І все так, як треба" },
        { en: "Never really thought I would make it",                       ua: "Ніколи й не думав, що в мене вийде" },
        { en: "Found someone who I don't think I'll ever replace and",      ua: "Знайшов ту, кого, гадаю, ніколи не заміню" },
        { en: "I'm emptying my heart, so you can just take it",             ua: "Я відкриваю своє серце навстіж — просто візьми його" },
        { en: "I'm living my best life",                                    ua: "Я живу своє найкраще життя" }
      ]},
      { label: "ПРИСПІВ", lines: [
        { en: "And I feel so alive",                                        ua: "І я почуваюся таким живим" },
        { en: "With you by my side",                                        ua: "Коли ти поруч зі мною" },
        { en: "We can make a life",                                         ua: "Ми можемо збудувати життя" },
        { en: "I've got nothing to hide",                                   ua: "Мені нема чого приховувати" },
        { en: "Driving so fast",                                            ua: "Мчимо так швидко" },
        { en: "Every town passed",                                          ua: "Кожне місто — позаду" },
        { en: "Never look back",                                            ua: "Ніколи не озираємось" },
        { en: "We're good at that",                                         ua: "У цьому ми майстри" },
        { en: "'Cause I feel so alive",                                     ua: "Бо я почуваюся таким живим" },
        { en: "Damn, you look good tonight",                                ua: "Чорт, ти сьогодні чудово виглядаєш" }
      ]},
      { label: "КУПЛЕТ 2", lines: [
        { en: "We're driving through rain",                                 ua: "Ми їдемо крізь дощ" },
        { en: "Running through sun",                                        ua: "Мчимо крізь сонце" },
        { en: "And looking at plains",                                      ua: "І дивимось на рівнини" },
        { en: "We're cruising through towns",                               ua: "Катаємось крізь міста" },
        { en: "Moving all around",                                          ua: "Раз у раз у русі" },
        { en: "But you stay the same",                                      ua: "Але ти лишаєшся незмінною" },
        { en: "We like to run away",                                        ua: "Ми любимо тікати геть" },
        { en: "We're ditching all our pain and living for today",          ua: "Ми кидаємо весь свій біль і живемо сьогоднішнім днем" },
        { en: "We're driving so fast",                                      ua: "Ми мчимо так швидко" },
        { en: "Wanna make it last, we'll do it our way",                   ua: "Хочемо, щоб це тривало, зробимо це по-своєму" },
        { en: "And I feel good at night",                                   ua: "І мені добре вночі" },
        { en: "Full moon the only light",                                   ua: "Повний місяць — єдине світло" },
        { en: "You make me feel like",                                      ua: "Поруч із тобою я відчуваю" },
        { en: "I'm doing alright",                                          ua: "Що в мене все гаразд" },
        { en: "I feel good inside",                                         ua: "Мені добре на душі" },
        { en: "Maybe a little high",                                        ua: "Можливо, трохи на підйомі" },
        { en: "You make me feel like",                                      ua: "Поруч із тобою я відчуваю" },
        { en: "Everything will be alright",                                 ua: "Що все буде добре" }
      ]},
      { label: "ПРИСПІВ", lines: [
        { en: "And I feel so alive",                                        ua: "І я почуваюся таким живим" },
        { en: "With you by my side",                                        ua: "Коли ти поруч зі мною" },
        { en: "We can make a life",                                         ua: "Ми можемо збудувати життя" },
        { en: "I've got nothing to hide",                                   ua: "Мені нема чого приховувати" },
        { en: "Driving so fast",                                            ua: "Мчимо так швидко" },
        { en: "Every town passed",                                          ua: "Кожне місто — позаду" },
        { en: "Never look back",                                            ua: "Ніколи не озираємось" },
        { en: "We're good at that",                                         ua: "У цьому ми майстри" },
        { en: "'Cause I feel so alive",                                     ua: "Бо я почуваюся таким живим" },
        { en: "Damn, you look good tonight",                                ua: "Чорт, ти сьогодні чудово виглядаєш" },
        { en: "And I feel so alive",                                        ua: "І я почуваюся таким живим" },
        { en: "With you by my side",                                        ua: "Коли ти поруч зі мною" },
        { en: "We can make a life",                                         ua: "Ми можемо збудувати життя" },
        { en: "I've got nothing to hide",                                   ua: "Мені нема чого приховувати" },
        { en: "Driving so fast",                                            ua: "Мчимо так швидко" },
        { en: "Every town passed",                                          ua: "Кожне місто — позаду" },
        { en: "Never look back",                                            ua: "Ніколи не озираємось" },
        { en: "We're good at that",                                         ua: "У цьому ми майстри" },
        { en: "'Cause I feel so alive",                                     ua: "Бо я почуваюся таким живим" },
        { en: "Damn, you look good tonight",                                ua: "Чорт, ти сьогодні чудово виглядаєш" }
      ]}
    ],
    glossary: {
      "damn": "чорт, до біса (підсилення)", "tonight": "сьогодні ввечері/вночі",
      "needed": "потребував (від need)", "something": "щось, дещо",
      "someone": "хтось", "trust": "довіряти; trust in — покладатися на",
      "through": "крізь, наскрізь; get me through — допомогти пройти",
      "coming": "наближення, поява; saw you coming — передбачити", "running": "мчимо, біжимо",
      "nothing": "нічого; make me feel nothing — тут: знімаєш тривоги",
      "driving": "їдемо, мчимо (за кермом)", "around": "навколо, довкола",
      "places": "місця", "seeing": "бачимо", "different": "різні, інші", "faces": "обличчя",
      "cruising": "катаємось, їдемо без поспіху", "playlist": "плейлист, добірка пісень",
      "everything": "усе", "really": "справді", "thought": "думав (від think)",
      "make it": "досягти успіху, впоратися", "found": "знайшов (від find)",
      "ever": "коли-небудь", "replace": "замінити", "emptying": "спорожнюю; тут: відкриваю навстіж",
      "heart": "серце", "take": "взяти", "living": "живу", "best": "найкращий",
      "alive": "живий", "side": "бік; by my side — поруч зі мною",
      "hide": "ховати, приховувати", "fast": "швидко", "town": "місто (невелике)",
      "passed": "минуло, лишилось позаду", "back": "назад; look back — озиратися",
      "good at": "майстер у чомусь, добре вмію", "rain": "дощ", "sun": "сонце",
      "plains": "рівнини, степи", "moving": "рухаємось", "same": "той самий, незмінний",
      "run away": "тікати, втікати", "ditching": "кидаємо, позбуваємось (ditch — кинути)",
      "pain": "біль", "today": "сьогодні", "last": "тривати; make it last — щоб тривало",
      "our way": "по-своєму, на свій лад", "night": "ніч", "full": "повний",
      "moon": "місяць", "only": "єдиний", "light": "світло",
      "alright": "гаразд, нормально (all right)", "inside": "всередині; feel good inside — добре на душі",
      "high": "на підйомі; під кайфом (тут радше «окрилений»)", "maybe": "можливо",
      "little": "трохи, трішки", "wanna": "хочу (want to)", "'cause": "бо (because)"
    },
    slang: [
      { en: "you look good tonight", ua: "ти сьогодні чудово виглядаєш", note: "комплімент; «damn» додає захоплення" },
      { en: "make it",               ua: "досягти успіху",               note: "«never thought I'd make it» — не вірив, що зможу" },
      { en: "make me feel nothing",  ua: "знімаєш усі тривоги",          note: "тут позитивне: поруч із нею зникають турботи (не «байдужість»)" },
      { en: "good at that",          ua: "у цьому ми майстри",           note: "«be good at» — добре щось уміти" },
      { en: "run away",              ua: "тікати геть",                  note: "втекти від проблем/буденності" },
      { en: "ditch",                 ua: "кинути, позбутися",            note: "ditch the pain — позбутися болю, лишити позаду" },
      { en: "make it last",          ua: "щоб це тривало",               note: "продовжити мить, не дати їй скінчитися" },
      { en: "do it our way",         ua: "робити по-своєму",             note: "жити за власними правилами" },
      { en: "feel high",             ua: "бути окриленим / під кайфом",  note: "тут радше емоційний підйом, ейфорія" }
    ]
  }
];

if (typeof window !== "undefined") { window.SONGS = SONGS; }
