/* ============================================================================
 * songs.js — дані для розділу «Пісні» (вивчення текстів NEFFEX тощо).
 * Підключається в index.html ПЕРЕД основним скриптом.
 *
 * Структура пісні:
 *   {
 *     id:      "унікальний-slug",      // ключ для статусу вивчення в localStorage
 *     artist:  "NEFFEX",
 *     title:   "Назва",
 *     ytId:    "YouTube video id",     // з https://youtube.com/watch?v=XXXX → "XXXX"
 *     sections: [ { label, lines: [ {en, ua} ] } ],
 *     glossary: { "слово": "переклад" } // hover для слів, яких НЕМАЄ в EN_TO_UA
 *                                       // (ключі — нижній регістр; апострофи можна)
 *     slang: [ {en, ua, note} ]         // ОКРЕМИЙ сленг/вирази (НЕ змішується з WORDS)
 *   }
 *
 * Назви секцій: ВСТУП · КУПЛЕТ 1/2/3 · ПРИСПІВ · ПРЕД-ПРИСПІВ · БРИДЖ · ПРОГРАШ · КІНЦІВКА
 * ========================================================================== */

const SONGS = [
  {
    id: "neffex-baller",
    artist: "NEFFEX",
    title: "Baller 🍾",
    ytId: "42JyRjrLzjY",
    sections: [
      { label: "КУПЛЕТ 1", lines: [
        { en: "Ooh, like Lebron though or like Lonzo",                ua: "У-у, наче Леброн, або як Лонзо" },
        { en: "Ooh, I'm a baller, yeah, shot caller",                 ua: "У-у, я крутій, так, я тут усе вирішую" },
        { en: "Yeah, they love me, you can't touch me",               ua: "Так, мене люблять, мене не дістати" },
        { en: "Nah, can't trust me, I'm too lucky",                   ua: "Не-а, мені не довіряй, я надто везучий" },
        { en: "Look at me, look at you, what you see, what you do",    ua: "Глянь на мене, глянь на себе — що ти бачиш, що ти робиш" },
        { en: "Baby, please, think it through, drink it up, enjoy the view", ua: "Крихітко, прошу, обдумай це, випий до дна, насолоджуйся краєвидом" },
        { en: "MVP, got my crew, Nike on my shoes",                   ua: "Найцінніший гравець, зі мною моя братва, Nike на кросівках" },
        { en: "Might be sippin' booze, slightly feelin' loose",       ua: "Може, потягую випивку, трохи розслабився" },
        { en: "If I want it, then I'll have it",                      ua: "Якщо я цього хочу — я це отримаю" },
        { en: "Got an iced wrist causin' damage",                     ua: "Зап'ястя в діамантах — аж сліпить" },
        { en: "Just like I planned it, I'll be damn rich",            ua: "Точно як і планував — буду до біса багатий" },
        { en: "Have a chef in the back, make a sandwich",             ua: "Маю кухаря там позаду — хай зробить сендвіч" },
        { en: "Ooh, she got it all, all, I just want it all, all",    ua: "У-у, у неї є все-все, а я просто хочу все-все" },
        { en: "Baby, we could ba-all, you just gotta fa-all",         ua: "Крихітко, ми могли б відриватися, тобі лиш треба піддатися" },
        { en: "I could be your ma-an, payin' for your ta-an",         ua: "Я міг би бути твоїм чоловіком, платити за твою засмагу" },
        { en: "I'm your biggest fa-an, you said this your ja-am, yeah (Yeah)", ua: "Я твій найбільший фанат, ти сказала — це твій улюблений трек, так (Так)" }
      ]},
      { label: "ПРИСПІВ", lines: [
        { en: "Oh, yeah, I'm livin' up life, like a baller (Baller)", ua: "О так, я живу на повну, як крутій (Крутій)" },
        { en: "I'm livin' like white, like I'm Walter (Like I'm Walter)", ua: "Живу шикарно, наче я Волтер (Наче я Волтер)" },
        { en: "She always call me, I never call her (Never call her)", ua: "Вона завжди дзвонить мені, я їй — ніколи (Ніколи їй)" },
        { en: "Oh, yeah, I'm livin' this life like a baller (Baller)", ua: "О так, я живу це життя як крутій (Крутій)" }
      ]},
      { label: "КУПЛЕТ 2", lines: [
        { en: "I pull up in a coup up in a Chevy",                    ua: "Під'їжджаю на купе, на Chevy" },
        { en: "I'ma hit it in the back, if she let me",               ua: "Зроблю своє на задньому сидінні, якщо вона дозволить" },
        { en: "And take your time, baby, gettin' ready",              ua: "І не поспішай, крихітко, збирайся" },
        { en: "I want you lookin' fine, oh, lookin' sexy, yeah, yeah", ua: "Хочу, щоб ти мала чудовий вигляд, о, сексуальний, так, так" },
        { en: "I be, I be, I be, I be, I be turnin' up",              ua: "Я відриваюсь, відриваюсь, відриваюсь" },
        { en: "Got no ID, ID, ID, ID, but she cute as fuck",          ua: "Без документів, але вона до біса мила" },
        { en: "So, I told her, she could kick it, but I said she couldn't touch", ua: "Тож я сказав, що вона може зависнути, але торкатися — зась" },
        { en: "Now, all she, all she, all she wants to do is kiss and hug", ua: "А тепер усе, чого вона хоче — цілуватись і обійматись" },
        { en: "I could go all day, I'ma do my thing",                 ua: "Я можу хоч цілий день, робитиму своє" },
        { en: "I'ma stay ballin', like it's my driveway",             ua: "Лишатимусь на коні, наче це моя під'їзна доріжка" },
        { en: "I'ma go all-in, party like Friday",                    ua: "Піду ва-банк, гулятиму як у п'ятницю" },
        { en: "I'ma take this day, turn it to my day",                ua: "Візьму цей день і зроблю його своїм" },
        { en: "Ooh, ooh, she love me, sippin' bubbly",                ua: "У-у, вона любить мене, попиваючи шампанське" },
        { en: "Champagne, cocaine, kiss and hug me",                  ua: "Шампанське, кокаїн, цілуй і обіймай мене" },
        { en: "It ain't nothin', droppin' money",                     ua: "Це дрібниці — смітити грошима" },
        { en: "Okay, all day, gettin' lucky, yeah (Yeah)",            ua: "Окей, цілий день щастить, так (Так)" }
      ]},
      { label: "ПРИСПІВ", lines: [
        { en: "Oh, yeah, I'm livin' up life, like a baller (Baller)", ua: "О так, я живу на повну, як крутій (Крутій)" },
        { en: "I'm livin' like white, like I'm Walter (Like I'm Walter)", ua: "Живу шикарно, наче я Волтер (Наче я Волтер)" },
        { en: "She always call me, I never call her (Never call her)", ua: "Вона завжди дзвонить мені, я їй — ніколи (Ніколи їй)" },
        { en: "Oh, yeah, I'm livin' this life like a baller (Baller)", ua: "О так, я живу це життя як крутій (Крутій)" }
      ]},
      { label: "КУПЛЕТ 3", lines: [
        { en: "Yeah, you can catch me in the studio",                 ua: "Так, можеш застати мене в студії" },
        { en: "Yeah, and you'll hear me on the radio",                ua: "Так, і почуєш мене по радіо" },
        { en: "Yeah, you'll hear me through your stereo",             ua: "Так, почуєш мене зі своєї стереосистеми" },
        { en: "Yeah, while I'm lookin' for my cameo",                 ua: "Так, поки я шукаю своє камео" },
        { en: "Yeah, she's textin' me, ooh, wanna get at me, ooh",    ua: "Так, вона пише мені, у-у, хоче підкотити, у-у" },
        { en: "Now she's sextin' me, yeah, she's testin' me",         ua: "Тепер шле мені пікантні повідомлення, так, випробовує мене" },
        { en: "I just let it be, yeah, I'm a vet, you see",           ua: "Я просто пускаю на самоплив, так, я бувалий, розумієш" },
        { en: "Since I was seventeen, welcome to the team, ooh, ooh", ua: "Ще з сімнадцяти, ласкаво просимо в команду, у-у" },
        { en: "Yeah, I deal in bulk, like I'm Costco",                ua: "Так, торгую оптом, наче я Costco" },
        { en: "Yeah, I got this shit on lock, though",                ua: "Так, я все тримаю під контролем" },
        { en: "Yeah, invest my money in my stock, oh",               ua: "Так, вкладаю гроші у свої акції, о" },
        { en: "Yeah, so, I'm growin' round the clock, yo",           ua: "Так, тож я росту цілодобово, йо" },
        { en: "Oh, she like that, wanna try that",                   ua: "О, їй таке подобається, хоче спробувати" },
        { en: "Wanna bite that, she got a nice ass",                 ua: "Хоче вкусити, у неї гарна дупа" },
        { en: "Tr-treat her right, yeah, she sippin' white, yeah",   ua: "Стався до неї добре, так, вона попиває біле, так" },
        { en: "We go all night, 'til we see the sunlight, yeah (Yeah)", ua: "Гуляємо всю ніч, поки не побачимо світанок, так (Так)" }
      ]},
      { label: "ПРИСПІВ", lines: [
        { en: "Oh, yeah, I'm livin' up life, like a baller (Baller)", ua: "О так, я живу на повну, як крутій (Крутій)" },
        { en: "I'm livin' like white, like I'm Walter (Like I'm Walter)", ua: "Живу шикарно, наче я Волтер (Наче я Волтер)" },
        { en: "She always call me, I never call her (Never call her)", ua: "Вона завжди дзвонить мені, я їй — ніколи (Ніколи їй)" },
        { en: "Oh, yeah, I'm livin' this life like a baller (Baller)", ua: "О так, я живу це життя як крутій (Крутій)" }
      ]}
    ],
    // hover-переклади слів (контекстні для цієї пісні; доповнюють основний словник)
    glossary: {
      "ooh": "у-у (вигук)", "nah": "не-а (ні)", "yo": "йо (вигук)",
      "lebron": "Леброн (Джеймс — баскетболіст)", "lonzo": "Лонзо (Болл — баскетболіст; гра слів з «ball»)",
      "baller": "крутій, успішний багатій", "shot": "постріл (тут: shot caller — головний)",
      "caller": "той, хто командує", "touch": "торкатися", "trust": "довіряти",
      "lucky": "везучий", "view": "краєвид, вид", "through": "крізь, наскрізь",
      "mvp": "найцінніший гравець (Most Valuable Player)", "crew": "команда, братва",
      "nike": "Nike (бренд)", "shoes": "взуття, кросівки", "might": "можливо, може",
      "sippin'": "потягую (sip — пити маленькими ковтками)", "booze": "випивка, алкоголь",
      "slightly": "трохи, злегка", "feelin'": "відчуваю", "loose": "розкутий, розслаблений",
      "iced": "у діамантах, в брильянтах", "wrist": "зап'ястя", "causin'": "спричиняє",
      "damage": "шкода (тут: «б'є наповал»)", "planned": "запланував", "damn": "до біса (підсилення)",
      "rich": "багатий", "chef": "шеф-кухар", "sandwich": "сендвіч", "gotta": "мусиш (got to)",
      "ball": "відриватися, розкошувати", "fall": "впасти; закохатися", "payin'": "плачу",
      "tan": "засмага", "biggest": "найбільший", "jam": "улюблений трек",
      "livin'": "живу", "walter": "Волтер (відсилання до Walter White, «Breaking Bad»)",
      "pull": "під'їжджати (pull up)", "coup": "купе (авто, coupe)", "chevy": "Chevy (Chevrolet)",
      "hit": "вдарити; тут «hit it» — переспати (натяк)", "gettin'": "стаю; gettin' ready — збираюсь",
      "ready": "готовий", "fine": "чудовий (вигляд)", "sexy": "сексуальний",
      "turnin'": "відриваюсь (turn up — тусити)", "cute": "милий, симпатичний",
      "kick": "копати; kick it — зависати, тусити", "kiss": "цілувати", "hug": "обіймати",
      "driveway": "під'їзна доріжка", "ballin'": "розкошую, живу красиво",
      "all-in": "ва-банк, поставити все", "party": "вечірка; гуляти",
      "bubbly": "шампанське (розм.)", "champagne": "шампанське", "cocaine": "кокаїн",
      "ain't": "не / немає (розм.)", "nothin'": "нічого, дрібниця", "droppin'": "смітити (грошима)",
      "studio": "студія", "radio": "радіо", "stereo": "стереосистема", "cameo": "камео, епізодична поява",
      "textin'": "пише повідомлення", "sextin'": "шле інтимні повідомлення (sexting)",
      "testin'": "випробовує", "vet": "бувалий, досвідчений (від veteran)",
      "seventeen": "сімнадцять", "team": "команда", "deal": "мати справу; торгувати",
      "bulk": "опт, великими партіями", "costco": "Costco (мережа гуртових магазинів)",
      "shit": "лайно (тут: «все це»)", "lock": "замок; on lock — під контролем",
      "invest": "вкладати, інвестувати", "stock": "акції", "growin'": "росту",
      "clock": "годинник; round the clock — цілодобово", "bite": "кусати",
      "ass": "дупа (груб.)", "treat": "ставитися; пригощати", "sunlight": "сонячне світло, світанок",
      "i'ma": "я зараз / я буду (I'm gonna)"
    },
    slang: [
      { en: "baller",          ua: "крутій, багатій",       note: "той, хто «грає по-крупному»; від баскетболу → успішна заможна людина" },
      { en: "shot caller",     ua: "головний, бос",          note: "той, хто приймає рішення і всім керує" },
      { en: "iced",            ua: "в діамантах",            note: "ice = діаманти; iced wrist — зап'ястя у брильянтах" },
      { en: "causin' damage",  ua: "б'є наповал",            note: "букв. «завдає шкоди» → справляє сильне враження" },
      { en: "ball / ballin'",  ua: "розкошувати",            note: "жити красиво, купатися в розкошах" },
      { en: "this your jam",   ua: "це твій улюблений трек", note: "jam — улюблена пісня" },
      { en: "livin' up life",  ua: "жити на повну",          note: "проживати життя на максимум" },
      { en: "like I'm Walter", ua: "як Волтер Вайт",         note: "відсилання до Walter White («Breaking Bad»); гра слів з «white» — і розкіш, і натяк" },
      { en: "hit it",          ua: "переспати",              note: "натяк (груб.-розм.)" },
      { en: "turn up",         ua: "відриватися",            note: "веселитися на повну, тусити" },
      { en: "kick it",         ua: "зависати",               note: "проводити час, тусити (без зобов'язань)" },
      { en: "as fuck",         ua: "до біса (груб.)",        note: "підсилювач: «cute as fuck» — неймовірно мила" },
      { en: "do my thing",     ua: "робити своє",            note: "займатися своєю справою, бути собою" },
      { en: "all-in",          ua: "ва-банк",                note: "поставити все, видатися повністю (з покеру)" },
      { en: "bubbly",          ua: "шампанське",             note: "розмовна назва шампанського (через бульбашки)" },
      { en: "droppin' money",  ua: "смітити грошима",        note: "багато й легко витрачати" },
      { en: "gettin' lucky",   ua: "щастить / переспати",    note: "подвійний сенс: і «везе», і інтимний натяк" },
      { en: "get at me",       ua: "підкотити",              note: "звертатися/залицятися, «дістатися» до когось" },
      { en: "sexting",         ua: "секстинг",               note: "обмін інтимними повідомленнями" },
      { en: "vet",             ua: "бувалий",                note: "досвідчений, «ветеран» своєї справи" },
      { en: "deal in bulk",    ua: "торгувати оптом",        note: "продавати великими партіями; гра слів з «deal» — оборудка" },
      { en: "on lock",         ua: "під контролем",          note: "повністю під контролем, «схоплено»" },
      { en: "round the clock", ua: "цілодобово",             note: "24/7, без перерви" },
      { en: "sippin' white",   ua: "попиває біле (вино)",    note: "ймовірно біле вино; можливий подвійний сенс" },
      { en: "coup",            ua: "купе",                   note: "від «coupe» — двомісне авто" },
      { en: "booze",           ua: "випивка",                note: "алкоголь (розм.)" }
    ]
  }
  ,
  {
    id: "neffex-lit",
    artist: "NEFFEX",
    title: "Lit 🔥",
    ytId: "AHhiRc0Lnq4",
    sections: [
      { label: "КУПЛЕТ 1", lines: [
        { en: "I'm just fuckin' lit, man, I'm just fuckin' lit",              ua: "Я просто до біса бухий, чуваку, просто бухий" },
        { en: "Drank a bottle of this shit, man, bottle of this shit",         ua: "Ковтнув пляшку цього добра, чуваку, пляшку" },
        { en: "I'm about to write a hit, man, about to write a hit",           ua: "Зараз напишу хіт, чуваку, напишу хіт" },
        { en: "No, I'm never gonna quit, man, never gonna quit",               ua: "Ні, я ніколи не здамся, чуваку, ніколи" },
        { en: "I just took another hit, man, took another hit",                ua: "Щойно ще разок затягнувся, чуваку, ще разок" },
        { en: "I'm about to lose my shit, man, about to lose my shit",         ua: "Зараз зірвусь, чуваку, зірвусь" },
        { en: "Does she have a fuckin' wristband? Yeah, she needs that shit",  ua: "У неї є браслет? Так, їй він потрібен" },
        { en: "Better get her out real quick, man, get her out real quick (Quick)", ua: "Краще виводь її звідси швидко, чуваку, швидко (Швидко)" }
      ]},
      { label: "ПРИСПІВ", lines: [
        { en: "Are you the present or the future? (Present or the future)",    ua: "Ти теперішнє чи майбутнє? (Теперішнє чи майбутнє)" },
        { en: "Are you a drinker or a boozer? (Drinker or a boozer)",          ua: "Ти п'єш по-людськи чи бухаєш? (П'єш чи бухаєш)" },
        { en: "Are you a giver or a user? (Giver or a user)",                  ua: "Ти даєш чи тільки береш? (Даєш чи береш)" },
        { en: "Are you a winner or a loser? (Winner or a loser)",              ua: "Ти переможець чи невдаха? (Переможець чи невдаха)" },
        { en: "Yeah, and I said that I would never back down",                 ua: "Так, і я казав, що ніколи не здамся" },
        { en: "And I said that I would never back down",                       ua: "І казав, що ніколи не здамся" },
        { en: "And I said that I would never back down",                       ua: "І казав, що ніколи не здамся" },
        { en: "I swore that I would never fuckin' back down",                  ua: "Клявся, що ніколи до біса не здамся" }
      ]},
      { label: "КУПЛЕТ 2", lines: [
        { en: "Pass the bottle and the fifth, man, bottle and the fifth",      ua: "Передай пляшку і п'ятак, чуваку, пляшку і п'ятак" },
        { en: "'Cause I'm feeling like the shit, man, feeling like the shit",  ua: "Бо я відчуваю себе вершиною, чуваку, вершиною" },
        { en: "Yeah, her body's like a gift, man, body's like a gift",         ua: "Так, її тіло — наче подарунок, чуваку, подарунок" },
        { en: "'Cause she's looking hella fit, man, looking hella fit",        ua: "Бо вона до біса у формі, чуваку, у формі" },
        { en: "And I can't always commit, man, can't always commit",           ua: "І я не завжди можу зобов'язуватись, чуваку" },
        { en: "Pull a trigger on this shit, man, trigger on this shit",        ua: "Вирішуюсь на це, чуваку, вирішуюсь" },
        { en: "'Cause I feel I haven't lived, man, feel I haven't lived",      ua: "Бо відчуваю, що не жив по-справжньому, чуваку" },
        { en: "'Til I got nothing to miss, man, got nothing to miss (Miss)",   ua: "Поки мені нема чого більше втрачати, чуваку (Втрачати)" }
      ]},
      { label: "ПРИСПІВ", lines: [
        { en: "Are you the present or the future? (Present or the future)",    ua: "Ти теперішнє чи майбутнє? (Теперішнє чи майбутнє)" },
        { en: "Are you a drinker or a boozer? (Drinker or a boozer)",          ua: "Ти п'єш по-людськи чи бухаєш? (П'єш чи бухаєш)" },
        { en: "Are you a giver or a user? (Giver or a user)",                  ua: "Ти даєш чи тільки береш? (Даєш чи береш)" },
        { en: "Are you a winner or a loser? (Winner or a loser)",              ua: "Ти переможець чи невдаха? (Переможець чи невдаха)" },
        { en: "Yeah, and I said that I would never back down",                 ua: "Так, і я казав, що ніколи не здамся" },
        { en: "And I said that I would never back down",                       ua: "І казав, що ніколи не здамся" },
        { en: "And I said that I would never back down",                       ua: "І казав, що ніколи не здамся" },
        { en: "I swore that I would never fuckin' back down",                  ua: "Клявся, що ніколи до біса не здамся" }
      ]}
    ],
    glossary: {
      "lit":       "бухий, п'яний (під кайфом)",
      "fuckin'":   "до біса (підсилення, груб.)",
      "man":       "чуваку (звернення)",
      "drank":     "випив (від drink)",
      "gonna":     "збираюся (going to)",
      "never":     "ніколи",
      "quit":      "здаватися, кидати",
      "took":      "взяв (від take)",
      "hit":       "хіт (пісня); тут: затягнутися",
      "lose":      "втрачати, зривати",
      "shit":      "лайно; тут: «добро», підсилення (груб.)",
      "wristband": "браслет (клубний — допуск на вечірку)",
      "real":      "справжній; real quick = дуже швидко",
      "quick":     "швидкий, швидко",
      "future":    "майбутнє",
      "drinker":   "той, хто п'є (помірно)",
      "boozer":    "п'яниця, бухар",
      "giver":     "той, хто дає",
      "user":      "той, хто бере/використовує (тут: споживач)",
      "winner":    "переможець",
      "loser":     "невдаха",
      "back":      "назад; back down — відступати",
      "down":      "вниз; back down — здаватися",
      "swore":     "клявся (від swear)",
      "swear":     "клястися",
      "'til":      "поки не (until)",
      "'cause":    "бо, тому що (because)",
      "pass":      "передати, подати",
      "fifth":     "п'ятак (750 мл пляшка — п'ята частина галона)",
      "feeling":   "відчуваю, відчуття",
      "body":      "тіло",
      "hella":     "дуже, до біса (каліфорнійський сленг)",
      "fit":       "у формі, підтягнутий/а",
      "gift":      "подарунок",
      "commit":    "зобов'язуватися (у стосунках)",
      "pull":      "тягнути; pull a trigger — натиснути на гашок",
      "trigger":   "курок, гашок; тут: вирішитися",
      "lived":     "жив (від live)",
      "nothing":   "нічого"
    },
    slang: [
      { en: "lit",                   ua: "бухий, п'яний",             note: "тут: п'яний/під кайфом (від алкоголю); ширше сленгове значення — «класний, у вогні»" },
      { en: "take a hit",            ua: "затягнутися",               note: "зробити затяжку (наркотичний натяк)" },
      { en: "lose my shit",          ua: "зірватися, збожеволіти",    note: "втратити контроль, вийти з себе" },
      { en: "wristband",             ua: "клубний браслет",           note: "браслет допуску на вечірку; без нього — виходь" },
      { en: "feeling like the shit", ua: "відчуваю себе вершиною",    note: "«the shit» (з артиклем) = найкращий, бог; без артикля — образа" },
      { en: "hella",                 ua: "дуже, до біса",             note: "каліфорнійський сленг-підсилювач (hella fit = неймовірно у формі)" },
      { en: "the fifth",             ua: "п'ятак (750 мл)",           note: "п'ята частина галона — стандартна пляшка міцного (США)" },
      { en: "commit",                ua: "зобов'язуватися",           note: "тут: у стосунках — «бути серйозним»" },
      { en: "pull a trigger",        ua: "натиснути на гашок",        note: "тут метафора: вирішитися на щось, зробити крок" },
      { en: "back down",             ua: "відступати, здаватися",     note: "back down = відмовлятися від позиції під тиском" },
      { en: "nothing to miss",       ua: "нема чого втрачати",        note: "коли вже все пережив — нема чого боятися" },
      { en: "boozer",                ua: "п'яниця, бухар",            note: "гірше ніж drinker: важкий алкоголік" },
      { en: "drinker vs boozer",     ua: "п'єш чи бухаєш",           note: "приспів ставить риторичні пари: даєш/береш, перемагаєш/програєш" },
      { en: "giver vs user",         ua: "даєш чи тільки береш",      note: "класичне протиставлення: той хто вкладає vs хто лише отримує" }
    ]
  }
  ,
  {
    id: "neffex-badass",
    artist: "NEFFEX",
    title: "Badass 💋",
    ytId: "rzElZuhGTpU",
    sections: [
      { label: "КУПЛЕТ 1", lines: [
        { en: "The wind is blowin' through her hair (Blowin' through her hair)", ua: "Вітер розвіває її волосся (Розвіває волосся)" },
        { en: "We like to head out on the road (Head out on the road)",          ua: "Ми любимо вирушати в дорогу (Вирушати в дорогу)" },
        { en: "And you know we don't really care (We don't really care)",        ua: "І знаєш, нам, по суті, байдуже (Нам байдуже)" },
        { en: "'Cause we're just doin' what we want (We're just doin' what we want)", ua: "Бо ми просто робимо, що хочемо (Робимо, що хочемо)" },
        { en: "She likes it when I treat her good (She likes it when I treat her good)", ua: "Їй подобається, коли я ставлюся до неї добре (коли ставлюся добре)" },
        { en: "She likes it when I treat her bad (She likes it when I treat her bad)",  ua: "Їй подобається, коли я ставлюся до неї погано (коли ставлюся погано)" },
        { en: "She likes to travel all around (That's right)",                   ua: "Вона любить мандрувати всюди (Саме так)" },
        { en: "I take her everywhere and back (Let's go, yeah)",                 ua: "Я вожу її скрізь і назад (Погнали, так)" },
        { en: "Oh, you fuckin' with the man, girl",                             ua: "О, ти зв'язалася зі справжнім мужиком, дівчино" },
        { en: "You throw it right back, know I like that, I'ma bite back",       ua: "Ти даєш відсіч, знаєш, мені таке до вподоби, і я кусну у відповідь" },
        { en: "You know, I've become a fan girl, the way you throwback",         ua: "Знаєш, я став твоїм фанатом — те, як ти все повертаєш у ретро-стилі" },
        { en: "Like a Kodak, girl, you own that",                               ua: "Наче кадр Kodak, дівчино, тобі це личить" },
        { en: "Cruise around with out a plan, girl",                            ua: "Катаємось без жодного плану, дівчино" },
        { en: "We'll never go back, girl, you know that you are so bad",         ua: "Ми ніколи не повернемось, дівчино, ти ж знаєш, яка ти відчайдушна" },
        { en: "Let's just spend a couple grand, girl",                          ua: "Давай просто спустимо пару тисяч, дівчино" },
        { en: "You know fuckin' with the man, girl (Man, girl, man, girl)",      ua: "Знаєш, ти зв'язалася зі справжнім мужиком, дівчино (Мужиком, дівчино)" }
      ]},
      { label: "ПРЕД-ПРИСПІВ", lines: [
        { en: "Yeah, oh, you could've been a good girl (Good girl)",             ua: "Так, о, ти могла б бути хорошою дівчинкою (Хорошою)" },
        { en: "But instead, you chose the real world (Real world)",              ua: "Але натомість ти обрала справжнє життя (Справжнє життя)" },
        { en: "Yeah, you've always been a savage (Savage)",                      ua: "Так, ти завжди була відчайдушною (Відчайдушна)" },
        { en: "Oh, you've always been a bad chick (Bad chick)",                  ua: "О, ти завжди була крутою дівкою (Крута дівка)" },
        { en: "I don't care if you got issues, daddy left, but I'm with you",    ua: "Мені байдуже, що в тебе проблеми, тато пішов — але я з тобою" },
        { en: "So, come with me never look back, we're livin' life like a badass", ua: "Тож ходи зі мною, не озирайся — ми живемо як справжні бунтарі" }
      ]},
      { label: "ПРИСПІВ", lines: [
        { en: "Yeah, oh, you could've been a good girl (Good girl)",             ua: "Так, о, ти могла б бути хорошою дівчинкою (Хорошою)" },
        { en: "But instead, you chose the real world (Real world)",              ua: "Але натомість ти обрала справжнє життя (Справжнє життя)" },
        { en: "Yeah, you've always been a savage (Savage)",                      ua: "Так, ти завжди була відчайдушною (Відчайдушна)" },
        { en: "Oh, you've always been a bad chick (Bad chick)",                  ua: "О, ти завжди була крутою дівкою (Крута дівка)" },
        { en: "I don't care if you got issues, daddy left, but I'm with you",    ua: "Мені байдуже, що в тебе проблеми, тато пішов — але я з тобою" },
        { en: "So, come with me never look back, we're livin' life like a badass", ua: "Тож ходи зі мною, не озирайся — ми живемо як справжні бунтарі" }
      ]},
      { label: "КУПЛЕТ 2", lines: [
        { en: "Yeah, cruisin' PCH with the top down",                           ua: "Так, мчимо по Тихоокеанському шосе з опущеним дахом" },
        { en: "Drop down, headed no where fast never stop now, not now",        ua: "Газу — і мчимо в нікуди, не зупиняємось, тільки не зараз" },
        { en: "We ain't slowin' down, never knowin' now",                       ua: "Ми не сповільнюємось, наперед нічого не знаємо" },
        { en: "We're just headin' south what it's all about",                   ua: "Просто прямуємо на південь — ось у чому вся суть" },
        { en: "Never had a doubt, yeah, she be sittin' shotgun",                ua: "Жодного сумніву, так, вона сидить поруч на передньому" },
        { en: "She a hot one, in the hot sun, crop top on, I'ma hop on",        ua: "Вона гаряча штучка, під палючим сонцем, у топику — я застрибую" },
        { en: "Every single day, head a different way",                         ua: "Щодня прямуємо в новий бік" },
        { en: "Never stay in place, don't care what they say",                  ua: "Ніколи не сидимо на місці, начхати, що кажуть" },
        { en: "We gon' do it anyway, always by my side",                        ua: "Ми все одно це зробимо, ти завжди поруч" },
        { en: "Oh, we're livin' life right, every night we just drive by",      ua: "О, ми живемо правильно, щоночі просто мчимо повз" },
        { en: "Cruisin' high life, we're alive, not just gettin' by",           ua: "Купаємось у розкошах, ми живі, а не просто животіємо" },
        { en: "Not just lettin' life pass right underneath our sight",          ua: "Не просто дивимось, як життя спливає в нас перед очима" },
        { en: "Grab it real tight, okay, every day is a new day",               ua: "Хапай його міцно, гаразд, кожен день — новий день" },
        { en: "In a new place, rent a new space, see a new face",               ua: "У новому місці, орендуємо нову хату, бачимо нове обличчя" },
        { en: "In a few days, move a new way to a new state",                   ua: "За кілька днів рушаємо по-новому в новий штат" },
        { en: "That's great, rent an estate for our next date, haha",           ua: "Це круто — орендуємо маєток для наступного побачення, ха-ха" }
      ]},
      { label: "ПРЕД-ПРИСПІВ", lines: [
        { en: "Yeah, oh, you could've been a good girl (Good girl)",             ua: "Так, о, ти могла б бути хорошою дівчинкою (Хорошою)" },
        { en: "But instead, you chose the real world (Real world)",              ua: "Але натомість ти обрала справжнє життя (Справжнє життя)" },
        { en: "Yeah, you've always been a savage (Savage)",                      ua: "Так, ти завжди була відчайдушною (Відчайдушна)" },
        { en: "Oh, you've always been a bad chick (Bad chick)",                  ua: "О, ти завжди була крутою дівкою (Крута дівка)" },
        { en: "I don't care if you got issues, daddy left, but I'm with you",    ua: "Мені байдуже, що в тебе проблеми, тато пішов — але я з тобою" },
        { en: "So, come with me never look back, we're livin' life like a badass", ua: "Тож ходи зі мною, не озирайся — ми живемо як справжні бунтарі" }
      ]},
      { label: "ПРИСПІВ", lines: [
        { en: "Yeah, oh, you could've been a good girl (Good girl)",             ua: "Так, о, ти могла б бути хорошою дівчинкою (Хорошою)" },
        { en: "But instead, you chose the real world (Real world)",              ua: "Але натомість ти обрала справжнє життя (Справжнє життя)" },
        { en: "Yeah, you've always been a savage (Savage)",                      ua: "Так, ти завжди була відчайдушною (Відчайдушна)" },
        { en: "Oh, you've always been a bad chick (Bad chick)",                  ua: "О, ти завжди була крутою дівкою (Крута дівка)" },
        { en: "I don't care if you got issues, daddy left, but I'm with you",    ua: "Мені байдуже, що в тебе проблеми, тато пішов — але я з тобою" },
        { en: "So, come with me never look back, we're livin' life like a badass", ua: "Тож ходи зі мною, не озирайся — ми живемо як справжні бунтарі" }
      ]}
    ],
    glossary: {
      "wind": "вітер", "blowin'": "дме, розвіває", "hair": "волосся",
      "head": "прямувати, рушати (head out — вирушати)", "road": "дорога",
      "really": "справді, по-справжньому", "care": "перейматися; don't care — байдуже",
      "doin'": "робимо", "treat": "ставитися (до когось)", "travel": "подорожувати, мандрувати",
      "everywhere": "скрізь, всюди", "fuckin'": "(груб. підсилення); fuckin' with — зв'язатися з",
      "man": "тут: справжній мужик, крутий", "throw": "кидати; throw it back — давати відсіч",
      "bite": "кусати; bite back — кусати/огризатися у відповідь",
      "fan": "фанат", "throwback": "ретро, повернення в минуле",
      "kodak": "Kodak (фотобренд; «кадр як на фото»)", "own": "володіти; you own that — тобі це личить",
      "cruise": "кататися, їхати без поспіху", "plan": "план",
      "couple": "пара, декілька", "grand": "тисяча доларів (сленг)",
      "could've": "міг/могла б (could have)", "instead": "натомість, замість",
      "chose": "обрав/обрала (від choose)", "real": "справжній, реальний",
      "world": "світ", "savage": "відчайдух; дикий, безбашений",
      "chick": "дівка, чувіха (розм.)", "issues": "проблеми (тут: внутрішні/у житті)",
      "daddy": "тато, татко", "left": "пішов, покинув (від leave)",
      "badass": "крутий бунтар, відчайдух", "cruisin'": "катаємось",
      "pch": "Тихоокеанське шосе (Pacific Coast Highway, Каліфорнія)",
      "top": "тут: дах авто (top down — з опущеним дахом)", "drop": "опускати; drop down — газонути/просісти",
      "headed": "прямую(ємо)", "nowhere": "нікуди", "stop": "зупинятися",
      "ain't": "не / немає (розм.)", "slowin'": "сповільнюємось", "knowin'": "знаючи",
      "headin'": "прямуємо", "south": "південь", "doubt": "сумнів",
      "shotgun": "переднє пасажирське сидіння (ride shotgun)", "hot": "гарячий; тут: сексуальна",
      "sun": "сонце", "crop": "укорочений (crop top — короткий топ)",
      "hop": "стрибати; hop on — застрибнути", "single": "кожен; every single day — буквально щодня",
      "different": "інший, різний", "place": "місце", "side": "бік; by my side — поруч зі мною",
      "right": "правильно; тут: як слід", "night": "ніч", "drive": "їхати; drive by — проїжджати повз",
      "high": "високий; high life — розкішне життя", "alive": "живий",
      "gettin'": "тут: gettin' by — ледь зводити кінці", "lettin'": "дозволяючи",
      "pass": "минати, спливати", "underneath": "під, попід", "sight": "погляд, поле зору",
      "grab": "хапати", "tight": "міцно, туго", "rent": "орендувати",
      "space": "простір; тут: житло, хата", "face": "обличчя", "state": "штат",
      "great": "чудово, круто", "estate": "маєток, садиба", "date": "побачення",
      "gon'": "збираємось (gonna / going to)", "anyway": "все одно, попри все"
    },
    slang: [
      { en: "badass",            ua: "крутий бунтар, відчайдух",   note: "сильна, безстрашна людина, що живе по-своєму (часто схвально)" },
      { en: "fuckin' with",      ua: "зв'язатися, мати справу",    note: "тут: «ти зв'язалася зі справжнім мужиком» (груб.-розм.)" },
      { en: "the man",           ua: "крутий мужик / головний",    note: "впевнений, авторитетний чоловік («він тут головний»)" },
      { en: "throw it back",     ua: "давати відсіч",              note: "відповідати тим самим, не пасувати" },
      { en: "bite back",         ua: "огризатися у відповідь",     note: "відповідати на випад так само різко" },
      { en: "you own that",      ua: "тобі це личить / це твоє",   note: "«own» тут = робити щось упевнено, на всі сто" },
      { en: "Kodak",             ua: "кадр як на фото",            note: "«Kodak moment» — ідеальна мить, варта знімка" },
      { en: "a couple grand",    ua: "пара тисяч (доларів)",       note: "grand = $1000 (сленг)" },
      { en: "savage",            ua: "відчайдух, безбашений",      note: "хтось зухвалий і безстрашний (схвально в сленгу)" },
      { en: "bad chick",         ua: "крута/відчайдушна дівка",    note: "тут «bad» = позитивне: ефектна, зухвала" },
      { en: "got issues",        ua: "мати проблеми",              note: "психологічні травми чи складнощі в житті" },
      { en: "the real world",    ua: "справжнє життя",             note: "життя без прикрас, на противагу «правильному»/тепличному" },
      { en: "ride shotgun",      ua: "сидіти на передньому",       note: "shotgun — переднє пасажирське сидіння поряд з водієм" },
      { en: "top down",          ua: "з опущеним дахом",           note: "про кабріолет — їхати з відкритим верхом" },
      { en: "PCH",               ua: "Тихоокеанське шосе",         note: "Pacific Coast Highway — мальовнича траса вздовж узбережжя Каліфорнії" },
      { en: "crop top",          ua: "укорочений топ",             note: "коротка майка, що відкриває живіт" },
      { en: "hop on",            ua: "застрибнути",                note: "швидко приєднатися/сісти" },
      { en: "high life",         ua: "розкішне життя",             note: "життя на широку ногу, в розкошах" },
      { en: "gettin' by",        ua: "ледь зводити кінці",         note: "виживати, абияк перебиватися (тут — те, чого вони НЕ роблять)" },
      { en: "hella",             ua: "дуже, до біса",              note: "(якщо трапиться) каліфорнійський сленг-підсилювач" }
    ]
  }
  ,
  {
    id: "neffex-new-beginnings",
    artist: "NEFFEX",
    title: "New Beginnings",
    ytId: "f4hcOJAXGxI",
    sections: [
      { label: "КУПЛЕТ 1", lines: [
        { en: "(Damn you look good tonight)",                                ua: "(Чорт, ти сьогодні чудово виглядаєш)" },
        { en: "I needed something",                                          ua: "Мені дечого бракувало" },
        { en: "Someone to trust in, yeah",                                   ua: "Когось, кому можна довіряти, так" },
        { en: "I needed something",                                          ua: "Мені дечого бракувало" },
        { en: "To get me through this life",                                 ua: "Чогось, щоб пройти крізь це життя" },
        { en: "Never saw you coming",                                        ua: "Не чекав на твою появу" },
        { en: "And now we're just running, yeah",                           ua: "А тепер ми просто мчимо, так" },
        { en: "You make me feel nothing",                                    ua: "Поруч із тобою зникають усі тривоги" },
        { en: "When we're driving through the night",                       ua: "Коли ми мчимо крізь ніч" },
        { en: "And I've been looking all around at the places",             ua: "І я роздивлявся навколо всі ці місця" },
        { en: "You and I were seeing so many different faces",              ua: "Ми з тобою бачили стільки різних облич" },
        { en: "We're just cruising right on through this life with a playlist", ua: "Ми просто катаємось крізь це життя під плейлист" },
        { en: "And everything is right",                                    ua: "І все так, як треба" },
        { en: "Never really thought I would make it",                       ua: "Ніколи й не думав, що в мене вийде" },
        { en: "Found someone who I don't think I'll ever replace and",      ua: "Знайшов ту, кого, гадаю, ніколи не заміню" },
        { en: "I'm emptying my heart, so you can just take it",             ua: "Я відкриваю своє серце навстіж — просто візьми його" },
        { en: "I'm living my best life",                                    ua: "Я живу своє найкраще життя" }
      ]},
      { label: "ПРИСПІВ", lines: [
        { en: "And I feel so alive",                                        ua: "І я почуваюся таким живим" },
        { en: "With you by my side",                                        ua: "Коли ти поруч зі мною" },
        { en: "We can make a life",                                         ua: "Ми можемо збудувати життя" },
        { en: "I've got nothing to hide",                                   ua: "Мені нема чого приховувати" },
        { en: "Driving so fast",                                            ua: "Мчимо так швидко" },
        { en: "Every town passed",                                          ua: "Кожне місто — позаду" },
        { en: "Never look back",                                            ua: "Ніколи не озираємось" },
        { en: "We're good at that",                                         ua: "У цьому ми майстри" },
        { en: "'Cause I feel so alive",                                     ua: "Бо я почуваюся таким живим" },
        { en: "Damn, you look good tonight",                                ua: "Чорт, ти сьогодні чудово виглядаєш" }
      ]},
      { label: "КУПЛЕТ 2", lines: [
        { en: "We're driving through rain",                                 ua: "Ми їдемо крізь дощ" },
        { en: "Running through sun",                                        ua: "Мчимо крізь сонце" },
        { en: "And looking at plains",                                      ua: "І дивимось на рівнини" },
        { en: "We're cruising through towns",                               ua: "Катаємось крізь міста" },
        { en: "Moving all around",                                          ua: "Раз у раз у русі" },
        { en: "But you stay the same",                                      ua: "Але ти лишаєшся незмінною" },
        { en: "We like to run away",                                        ua: "Ми любимо тікати геть" },
        { en: "We're ditching all our pain and living for today",          ua: "Ми кидаємо весь свій біль і живемо сьогоднішнім днем" },
        { en: "We're driving so fast",                                      ua: "Ми мчимо так швидко" },
        { en: "Wanna make it last, we'll do it our way",                   ua: "Хочемо, щоб це тривало, зробимо це по-своєму" },
        { en: "And I feel good at night",                                   ua: "І мені добре вночі" },
        { en: "Full moon the only light",                                   ua: "Повний місяць — єдине світло" },
        { en: "You make me feel like",                                      ua: "Поруч із тобою я відчуваю" },
        { en: "I'm doing alright",                                          ua: "Що в мене все гаразд" },
        { en: "I feel good inside",                                         ua: "Мені добре на душі" },
        { en: "Maybe a little high",                                        ua: "Можливо, трохи на підйомі" },
        { en: "You make me feel like",                                      ua: "Поруч із тобою я відчуваю" },
        { en: "Everything will be alright",                                 ua: "Що все буде добре" }
      ]},
      { label: "ПРИСПІВ", lines: [
        { en: "And I feel so alive",                                        ua: "І я почуваюся таким живим" },
        { en: "With you by my side",                                        ua: "Коли ти поруч зі мною" },
        { en: "We can make a life",                                         ua: "Ми можемо збудувати життя" },
        { en: "I've got nothing to hide",                                   ua: "Мені нема чого приховувати" },
        { en: "Driving so fast",                                            ua: "Мчимо так швидко" },
        { en: "Every town passed",                                          ua: "Кожне місто — позаду" },
        { en: "Never look back",                                            ua: "Ніколи не озираємось" },
        { en: "We're good at that",                                         ua: "У цьому ми майстри" },
        { en: "'Cause I feel so alive",                                     ua: "Бо я почуваюся таким живим" },
        { en: "Damn, you look good tonight",                                ua: "Чорт, ти сьогодні чудово виглядаєш" },
        { en: "And I feel so alive",                                        ua: "І я почуваюся таким живим" },
        { en: "With you by my side",                                        ua: "Коли ти поруч зі мною" },
        { en: "We can make a life",                                         ua: "Ми можемо збудувати життя" },
        { en: "I've got nothing to hide",                                   ua: "Мені нема чого приховувати" },
        { en: "Driving so fast",                                            ua: "Мчимо так швидко" },
        { en: "Every town passed",                                          ua: "Кожне місто — позаду" },
        { en: "Never look back",                                            ua: "Ніколи не озираємось" },
        { en: "We're good at that",                                         ua: "У цьому ми майстри" },
        { en: "'Cause I feel so alive",                                     ua: "Бо я почуваюся таким живим" },
        { en: "Damn, you look good tonight",                                ua: "Чорт, ти сьогодні чудово виглядаєш" }
      ]}
    ],
    glossary: {
      "damn": "чорт, до біса (підсилення)", "tonight": "сьогодні ввечері/вночі",
      "needed": "потребував (від need)", "something": "щось, дещо",
      "someone": "хтось", "trust": "довіряти; trust in — покладатися на",
      "through": "крізь, наскрізь; get me through — допомогти пройти",
      "coming": "наближення, поява; saw you coming — передбачити", "running": "мчимо, біжимо",
      "nothing": "нічого; make me feel nothing — тут: знімаєш тривоги",
      "driving": "їдемо, мчимо (за кермом)", "around": "навколо, довкола",
      "places": "місця", "seeing": "бачимо", "different": "різні, інші", "faces": "обличчя",
      "cruising": "катаємось, їдемо без поспіху", "playlist": "плейлист, добірка пісень",
      "everything": "усе", "really": "справді", "thought": "думав (від think)",
      "make it": "досягти успіху, впоратися", "found": "знайшов (від find)",
      "ever": "коли-небудь", "replace": "замінити", "emptying": "спорожнюю; тут: відкриваю навстіж",
      "heart": "серце", "take": "взяти", "living": "живу", "best": "найкращий",
      "alive": "живий", "side": "бік; by my side — поруч зі мною",
      "hide": "ховати, приховувати", "fast": "швидко", "town": "місто (невелике)",
      "passed": "минуло, лишилось позаду", "back": "назад; look back — озиратися",
      "good at": "майстер у чомусь, добре вмію", "rain": "дощ", "sun": "сонце",
      "plains": "рівнини, степи", "moving": "рухаємось", "same": "той самий, незмінний",
      "run away": "тікати, втікати", "ditching": "кидаємо, позбуваємось (ditch — кинути)",
      "pain": "біль", "today": "сьогодні", "last": "тривати; make it last — щоб тривало",
      "our way": "по-своєму, на свій лад", "night": "ніч", "full": "повний",
      "moon": "місяць", "only": "єдиний", "light": "світло",
      "alright": "гаразд, нормально (all right)", "inside": "всередині; feel good inside — добре на душі",
      "high": "на підйомі; під кайфом (тут радше «окрилений»)", "maybe": "можливо",
      "little": "трохи, трішки", "wanna": "хочу (want to)", "'cause": "бо (because)"
    },
    slang: [
      { en: "you look good tonight", ua: "ти сьогодні чудово виглядаєш", note: "комплімент; «damn» додає захоплення" },
      { en: "make it",               ua: "досягти успіху",               note: "«never thought I'd make it» — не вірив, що зможу" },
      { en: "make me feel nothing",  ua: "знімаєш усі тривоги",          note: "тут позитивне: поруч із нею зникають турботи (не «байдужість»)" },
      { en: "good at that",          ua: "у цьому ми майстри",           note: "«be good at» — добре щось уміти" },
      { en: "run away",              ua: "тікати геть",                  note: "втекти від проблем/буденності" },
      { en: "ditch",                 ua: "кинути, позбутися",            note: "ditch the pain — позбутися болю, лишити позаду" },
      { en: "make it last",          ua: "щоб це тривало",               note: "продовжити мить, не дати їй скінчитися" },
      { en: "do it our way",         ua: "робити по-своєму",             note: "жити за власними правилами" },
      { en: "feel high",             ua: "бути окриленим / під кайфом",  note: "тут радше емоційний підйом, ейфорія" }
    ]
  }
  ,
  {
    id: "neffex-all-these-thoughts",
    artist: "NEFFEX",
    title: "All These Thoughts",
    ytId: "uemkb0PpW3c",
    sections: [
      { label: "ВСТУП", lines: [
        { en: "Yo, all these thoughts keep me up at night, yeah",            ua: "Йо, усі ці думки не дають мені спати ночами, так" },
        { en: "What am I doin', did I do it right? Yeah",                    ua: "Що я роблю, чи правильно я вчинив? Так" },
        { en: "All these thoughts keep me up at night, yeah",               ua: "Усі ці думки не дають мені спати ночами, так" },
        { en: "I can't think straight, need the light, yo (Yo)",            ua: "Я не можу мислити ясно, мені потрібне світло, йо (Йо)" }
      ]},
      { label: "КУПЛЕТ 1", lines: [
        { en: "I need to breathe, get me up and out of these sheets",       ua: "Мені треба дихати, підняти себе й вибратися з-під ковдри" },
        { en: "Onto my feet, another cup of coffee in me",                  ua: "Стати на ноги, ще одна чашка кави в мене всередині" },
        { en: "That's what I need, my eyes puffy, I can't see",             ua: "Ось що мені треба, очі набряклі, я нічого не бачу" },
        { en: "I'm too tired to function, but too lost to sleep, ay",       ua: "Надто втомлений, щоб функціонувати, та надто розгублений, щоб спати, ей" },
        { en: "I think I need to be on somethin', medication",              ua: "Думаю, мені треба щось приймати, якісь ліки" },
        { en: "I think I need to figure out this segregation",              ua: "Думаю, мені треба розібратися в цьому розладі всередині" },
        { en: "I think I needed just a better education",                   ua: "Думаю, мені просто бракувало кращої освіти" },
        { en: "To understand a world that's so complicated",               ua: "Щоб зрозуміти світ, який такий заплутаний" },
        { en: "Intoxicated, every night, faded, just so I can sleep",       ua: "Сп'янілий щоночі, у відключці — лише щоб заснути" },
        { en: "Thinkin' that it's aidin', I feel hated, I feel hatred",     ua: "Думаю, що це помагає; я почуваюся знедоленим, у мені сама ненависть" },
        { en: "I'm lost, deep in my mind that I've created",               ua: "Я загубився глибоко в розумі, який сам собі створив" },
        { en: "I have dreams where my life is devastated",                 ua: "Мені сняться сни, де моє життя зруйноване" },
        { en: "Feels so real that I wake up shaken",                       ua: "Це таке справжнє, що я прокидаюся приголомшений" },
        { en: "Need thicker skin 'cause this life is no haven",            ua: "Треба грубшу шкіру, бо це життя — не тихий прихисток" },
        { en: "Nod your head if you get what I'm sayin'",                  ua: "Кивни головою, якщо розумієш, про що я" }
      ]},
      { label: "ПРИСПІВ", lines: [
        { en: "Yo, all these thoughts keep me up at night, yeah (Keep me up at night)", ua: "Йо, усі ці думки не дають мені спати ночами, так (Не дають спати)" },
        { en: "What am I doin', did I do it right? Yeah (Did I do it right?)",          ua: "Що я роблю, чи правильно я вчинив? Так (Чи правильно вчинив?)" },
        { en: "All these thoughts keep me up at night, yeah (Keep me up at night)",     ua: "Усі ці думки не дають мені спати ночами, так (Не дають спати)" },
        { en: "I can't think straight, need the light (Need the light)",               ua: "Я не можу мислити ясно, мені потрібне світло (Потрібне світло)" },
        { en: "Yo, all these thoughts keep me up at night, yeah (Keep me up at night)", ua: "Йо, усі ці думки не дають мені спати ночами, так (Не дають спати)" },
        { en: "What am I doin', did I do it right? Yeah (Did I do it right?)",          ua: "Що я роблю, чи правильно я вчинив? Так (Чи правильно вчинив?)" },
        { en: "All these thoughts keep me up at night, yeah (Keep me up at night)",     ua: "Усі ці думки не дають мені спати ночами, так (Не дають спати)" },
        { en: "I can't think straight, need the light (Need the light)",               ua: "Я не можу мислити ясно, мені потрібне світло (Потрібне світло)" }
      ]},
      { label: "КУПЛЕТ 2", lines: [
        { en: "I don't really think I understand this world, no",          ua: "Я, чесно, не думаю, що розумію цей світ, ні" },
        { en: "Got my head spinnin' 'round in a circle",                   ua: "Голова йде обертом, по колу" },
        { en: "Everybody lacks what they need internal",                  ua: "Усім бракує того, що потрібно всередині" },
        { en: "So, they compensate with everythin' external",            ua: "Тож вони компенсують це всім зовнішнім" },
        { en: "Not tryna throw shade, hah, no way",                       ua: "Не хочу нікого принижувати, ха, ні-ні" },
        { en: "I'm just tryin' to find the meanin' of life, hey",         ua: "Я просто намагаюся знайти сенс життя, гей" },
        { en: "There's happiness if you try to live the right way",       ua: "Щастя є, якщо намагаєшся жити правильно" },
        { en: "Forget about what others have and live your life, hey",    ua: "Забудь про те, що мають інші, і живи своїм життям, гей" },
        { en: "Be aware of who you are, what you're good at",             ua: "Усвідом, хто ти є, у чому ти сильний" },
        { en: "Take a step forward, see where your foot's at",            ua: "Зроби крок уперед, поглянь, куди ступає твоя нога" },
        { en: "Stand tall, stand proud, talk loud",                       ua: "Тримайся гідно, тримайся гордо, говори голосно" },
        { en: "Every word out your mouth has purpose now",               ua: "Кожне слово з твоїх вуст тепер має сенс" },
        { en: "You just gotta get rid of the bad thoughts",              ua: "Тобі лиш треба позбутися поганих думок" },
        { en: "Hatin' others 'cause you know that they got a lot",        ua: "Тих, де ненавидиш інших за те, що в них багато" },
        { en: "Forget that though, you got plenty",                       ua: "Та забудь про це — у тебе й так удосталь" },
        { en: "You're alive in this life, you got time, go get it, oh",   ua: "Ти живий у цьому житті, у тебе є час — іди й бери своє, о" }
      ]},
      { label: "ПРИСПІВ", lines: [
        { en: "Yo, all these thoughts keep me up at night, yeah (Yeah)",   ua: "Йо, усі ці думки не дають мені спати ночами, так (Так)" },
        { en: "What am I doin', did I do it right? Yeah (Yeah)",           ua: "Що я роблю, чи правильно я вчинив? Так (Так)" },
        { en: "All these thoughts keep me up at night, yeah (Yeah)",      ua: "Усі ці думки не дають мені спати ночами, так (Так)" },
        { en: "I can't think straight, need the light, oh (Oh)",          ua: "Я не можу мислити ясно, мені потрібне світло, о (О)" },
        { en: "Yo, all these thoughts keep me up at night, yeah (Yeah)",   ua: "Йо, усі ці думки не дають мені спати ночами, так (Так)" },
        { en: "What am I doin', did I do it right? Yeah (Yeah)",           ua: "Що я роблю, чи правильно я вчинив? Так (Так)" },
        { en: "All these thoughts keep me up at night, yeah (Yeah)",      ua: "Усі ці думки не дають мені спати ночами, так (Так)" },
        { en: "I can't think straight, need the light, oh (Oh)",          ua: "Я не можу мислити ясно, мені потрібне світло, о (О)" }
      ]}
    ],
    glossary: {
      "yo": "йо (вигук)", "thoughts": "думки", "keep": "тримати; keep me up — не дає спати",
      "doin'": "роблю", "straight": "прямо; think straight — мислити ясно",
      "light": "світло", "breathe": "дихати", "sheets": "простирадла, постіль",
      "onto": "на; onto my feet — стати на ноги", "feet": "ноги (ступні)",
      "cup": "чашка", "coffee": "кава", "puffy": "набряклий, опухлий",
      "tired": "втомлений", "function": "функціонувати, діяти", "lost": "загублений, розгублений",
      "somethin'": "щось", "medication": "ліки, медикаменти",
      "figure": "збагнути (figure out — розібратися)", "segregation": "розділення; тут: внутрішній розлад",
      "education": "освіта", "understand": "розуміти", "complicated": "складний, заплутаний",
      "intoxicated": "сп'янілий, одурманений", "faded": "у відключці (під кайфом/п'яний)",
      "aidin'": "помагає (aid — допомагати)", "hated": "зненавиджений, знедолений",
      "hatred": "ненависть", "deep": "глибоко", "mind": "розум, свідомість",
      "created": "створив", "dreams": "сни, мрії", "devastated": "зруйноване, спустошене",
      "real": "справжній, реальний", "wake": "прокидатися", "shaken": "приголомшений, потрясений",
      "thicker": "грубший, товщий", "skin": "шкіра; thick skin — стійкість до критики",
      "haven": "прихисток, гавань", "nod": "кивати", "sayin'": "кажу",
      "spinnin'": "крутиться, обертається", "circle": "коло",
      "everybody": "усі, кожен", "lacks": "бракує, не вистачає", "internal": "внутрішній",
      "compensate": "компенсувати, відшкодовувати", "external": "зовнішній",
      "tryna": "намагаюся (trying to)", "shade": "тінь; throw shade — принижувати, кпити",
      "meanin'": "сенс, значення", "happiness": "щастя", "forget": "забувати",
      "others": "інші", "aware": "обізнаний; be aware — усвідомлювати",
      "step": "крок", "forward": "вперед", "foot": "нога (ступня)",
      "tall": "високий; stand tall — триматися гідно", "proud": "гордий",
      "loud": "голосно", "mouth": "рот, вуста", "purpose": "мета, сенс",
      "gotta": "мусиш (got to)", "rid": "позбутися (get rid of)",
      "hatin'": "ненавидіти", "plenty": "удосталь, багато", "alive": "живий",
      "'cause": "бо (because)", "though": "втім, проте"
    },
    slang: [
      { en: "keep me up at night", ua: "не дає спати ночами",         note: "тривожні думки, через які не заснути" },
      { en: "think straight",      ua: "мислити ясно",                note: "тверезо, чітко розмірковувати" },
      { en: "on something",        ua: "щось приймати (ліки/наркотики)", note: "«be on medication» — сидіти на ліках" },
      { en: "faded",               ua: "у відключці",                 note: "сильно п'яний або під кайфом" },
      { en: "intoxicated",         ua: "сп'янілий, одурманений",      note: "під дією алкоголю чи речовин" },
      { en: "thick skin",          ua: "товста шкіра",                note: "стійкість до критики й образ, незворушність" },
      { en: "throw shade",         ua: "принижувати, кпити",          note: "тонко знущатися, виявляти зневагу" },
      { en: "head spinning",       ua: "голова йде обертом",          note: "від перевантаження думками/розгубленості" },
      { en: "stand tall",          ua: "триматися гідно",             note: "не пасувати, поводитись упевнено й гордо" },
      { en: "get rid of",          ua: "позбутися",                   note: "звільнитися від чогось небажаного" },
      { en: "go get it",           ua: "іди й бери своє",             note: "заклик діяти, домагатися мети" }
    ]
  }
  ,
  {
    id: "neffex-flirt",
    artist: "NEFFEX",
    title: "Flirt 💋",
    ytId: "eIeWkOZKidM",
    sections: [
      { label: "ПРИСПІВ", lines: [
        { en: "She just wants to flirt, so, I flirt right back (Right back)", ua: "Вона просто хоче фліртувати — тож і я фліртую у відповідь (У відповідь)" },
        { en: "I just put in work, yeah, I work like that",                  ua: "Я просто викладаюся, так, я працюю саме так" },
        { en: "Got me fallin', man, it hurts, yeah, it hurts so bad (Bad)",  ua: "Я закохуюся, чуваку, і це болить, так, болить до нестями (До нестями)" },
        { en: "All-in and it's worth everything I have (I have)",            ua: "Іду ва-банк, і це варте всього, що в мене є (Що маю)" }
      ]},
      { label: "КУПЛЕТ 1", lines: [
        { en: "I could feel the butterflies multiply",                      ua: "Я відчував, як метелики в животі розмножуються" },
        { en: "Every time I meet your eyes, amplified",                     ua: "Щоразу, як зустрічаю твій погляд, — усе сильніше" },
        { en: "Deep inside, once I feel your skin on mine",                 ua: "Десь глибоко, щойно відчую твою шкіру на своїй" },
        { en: "Though I try, I can't hide all the ways I feel inside",      ua: "Хоч і намагаюсь, не можу приховати всього, що відчуваю всередині" },
        { en: "You're everything I want in life (Life)",                    ua: "Ти — усе, чого я хочу в житті (Житті)" }
      ]},
      { label: "ПРИСПІВ", lines: [
        { en: "She just wants to flirt, so, I flirt right back (Right back)", ua: "Вона просто хоче фліртувати — тож і я фліртую у відповідь (У відповідь)" },
        { en: "I just put in work, yeah, I work like that",                  ua: "Я просто викладаюся, так, я працюю саме так" },
        { en: "Got me fallin', man, it hurts, yeah, it hurts so bad (Bad)",  ua: "Я закохуюся, чуваку, і це болить, так, болить до нестями (До нестями)" },
        { en: "All-in and it's worth everything I have (I have)",            ua: "Іду ва-банк, і це варте всього, що в мене є (Що маю)" }
      ]},
      { label: "КУПЛЕТ 2", lines: [
        { en: "Got a body and she naughty, never want her off me",          ua: "Тіло — вогонь, і вона пустунка, не хочу відпускати її від себе" },
        { en: "Hot like wasabi, hot like some coffee",                      ua: "Гаряча, як васабі, гаряча, як кава" },
        { en: "We drink like a hobby, like to get sloppy",                  ua: "Ми п'ємо, як на хобі, любимо набратися до чортиків" },
        { en: "We ain't never stoppin', yeah (Yeah)",                       ua: "Ми ніколи не зупиняємось, так (Так)" },
        { en: "I just wanna drink with this girl all day (All day)",        ua: "Я просто хочу пити з цією дівчиною цілий день (Цілий день)" },
        { en: "I don't wanna think, I just want to play",                   ua: "Не хочу думати, просто хочу гратися" },
        { en: "Keep me underneath the sheets while we sleep all day (All day)", ua: "Тримай мене під ковдрою, поки ми спимо цілий день (Цілий день)" },
        { en: "I just wanna feed everything I crave (I crave)",             ua: "Я просто хочу втамувати все, чого так прагну (Прагну)" },
        { en: "I recall the first day that I met you",                      ua: "Я згадую той перший день, коли зустрів тебе" },
        { en: "How could I forget you? No, I don't regret you",            ua: "Як я міг би тебе забути? Ні, я не шкодую про тебе" },
        { en: "Hope I don't upset you, I miss layin' in bed, too",         ua: "Сподіваюсь, не засмучую тебе; я теж сумую за тим, як ми лежали в ліжку" },
        { en: "Your head up on my chest, you we're never second best, boo (Boo)", ua: "Твоя голова в мене на грудях — ти ніколи не була другосортною, кохана (Кохана)" },
        { en: "Sippin' on some liquor, we remember all the good times",     ua: "Потягуючи міцне, ми згадуємо всі хороші часи" },
        { en: "Live a little quicker, thinkin' bigger, wish we could climb", ua: "Жити трохи швидше, мислити масштабніше, шкода, що не можемо злетіти вище" },
        { en: "Look up in the mirror, seein' clearer for our first time",   ua: "Дивлюсь у дзеркало й уперше бачу все чіткіше" },
        { en: "Just a couple sinners, man, I wish I could reverse time (Reverse time)", ua: "Просто двоє грішників, чуваку, шкода, що не можу повернути час назад (Назад)" },
        { en: "Yeah, we fake it 'til we make it or we break it off and hate it", ua: "Так, ми вдаємо, поки не вийде по-справжньому, або рвемо все й ненавидимо це" },
        { en: "Gettin' faded, gettin' naked, every time I feel impatient",  ua: "Напиваємось, роздягаємось щоразу, коли мене беруть нетерплячка" },
        { en: "And sometimes, I can't escape it, I just want to feel your shape and (Yeah)", ua: "І часом я не можу від цього втекти — просто хочу відчувати твої форми, і (Так)" },
        { en: "Like my dreams, I can't sit back, I have to chase 'em (Chase 'em)", ua: "Як і свої мрії, я не можу сидіти склавши руки — мушу гнатися за ними (Гнатися)" }
      ]},
      { label: "ПРИСПІВ", lines: [
        { en: "She just wants to flirt, so, I flirt right back (Right back)", ua: "Вона просто хоче фліртувати — тож і я фліртую у відповідь (У відповідь)" },
        { en: "I just put in work, yeah, I work like that",                  ua: "Я просто викладаюся, так, я працюю саме так" },
        { en: "Got me fallin', man, it hurts, yeah, it hurts so bad (Bad)",  ua: "Я закохуюся, чуваку, і це болить, так, болить до нестями (До нестями)" },
        { en: "All-in and it's worth everything I have (I have)",            ua: "Іду ва-банк, і це варте всього, що в мене є (Що маю)" }
      ]},
      { label: "КІНЦІВКА", lines: [
        { en: "She just wants to flirt, so, I flirt right back (Right back)", ua: "Вона просто хоче фліртувати — тож і я фліртую у відповідь (У відповідь)" },
        { en: "I just put in work, yeah, I work like that",                  ua: "Я просто викладаюся, так, я працюю саме так" },
        { en: "Got me fallin', man, it hurts, yeah, it hurts so bad (Bad)",  ua: "Я закохуюся, чуваку, і це болить, так, болить до нестями (До нестями)" },
        { en: "All-in and it's worth everything I have (I have)",            ua: "Іду ва-банк, і це варте всього, що в мене є (Що маю)" }
      ]}
    ],
    glossary: {
      "flirt": "фліртувати, загравати", "right": "тут: у відповідь (right back)",
      "back": "назад; right back — у відповідь", "put": "вкладати; put in work — викладатися",
      "work": "робота; працювати, старатися", "fallin'": "падаю; тут: закохуюся (fall for)",
      "man": "чуваку (звернення)", "hurts": "болить", "bad": "тут: «до нестями», сильно",
      "all-in": "ва-банк, поставити все (з покеру)", "worth": "вартий, варте",
      "butterflies": "метелики (в животі — хвилювання від закоханості)", "multiply": "розмножуватися, множитися",
      "amplified": "підсилений, гучніший", "deep": "глибоко", "inside": "всередині",
      "once": "щойно, як тільки", "skin": "шкіра", "mine": "моя/моє",
      "though": "хоч, попри", "hide": "приховувати", "ways": "способи; тут: усе, що відчуваю",
      "body": "тіло", "naughty": "пустотлива, грайливо-неслухняна", "off": "геть; off me — від мене",
      "hot": "гаряча; тут: сексуальна", "wasabi": "васабі (гострий зелений хрін)", "coffee": "кава",
      "hobby": "хобі, захоплення", "sloppy": "неохайний; get sloppy — набратися, перебрати",
      "stoppin'": "зупиняємось", "wanna": "хочу (want to)", "play": "гратися, бавитися",
      "underneath": "під, попід", "sheets": "простирадла, постіль", "feed": "годувати; тут: вдовольняти",
      "crave": "жадати, прагнути", "recall": "згадувати, пригадувати", "forget": "забути",
      "regret": "шкодувати", "hope": "сподіватися", "upset": "засмучувати",
      "miss": "сумувати за", "layin'": "лежати (lying)", "bed": "ліжко",
      "head": "голова", "chest": "груди", "second best": "другосортний, гірший вибір",
      "boo": "кохана/коханий (лагідне звертання)", "sippin'": "потягую (пити дрібними ковтками)",
      "liquor": "міцний алкоголь", "remember": "пам'ятати", "quicker": "швидше",
      "thinkin'": "думаючи; think bigger — мислити масштабніше", "bigger": "більше, масштабніше",
      "wish": "бажати, шкодувати (що не…)", "climb": "лізти вгору, підійматися",
      "mirror": "дзеркало", "clearer": "чіткіше, ясніше", "couple": "пара, двоє",
      "sinners": "грішники", "reverse": "повертати назад, обертати", "fake": "вдавати, підробляти",
      "make it": "досягти успіху", "break": "ламати; break it off — порвати стосунки",
      "hate": "ненавидіти", "faded": "напідпитку, у відключці", "naked": "голий",
      "impatient": "нетерплячий", "sometimes": "інколи, часом", "escape": "втекти, уникнути",
      "shape": "форма (тіла), обриси", "dreams": "мрії, сни", "chase": "гнатися, переслідувати",
      "'em": "їх (them)", "ain't": "не / немає (розм.)"
    },
    slang: [
      { en: "flirt right back",   ua: "фліртувати у відповідь",      note: "відповідати на загравання тим самим" },
      { en: "put in work",        ua: "викладатися, старатися",      note: "докладати зусиль (у стосунках/справі)" },
      { en: "fall for someone",   ua: "закохатися",                  note: "«got me fallin'» — я в неї закохуюся" },
      { en: "all-in",             ua: "ва-банк",                     note: "поставити все, віддатися повністю (з покеру)" },
      { en: "butterflies",        ua: "метелики в животі",           note: "приємне хвилювання від закоханості" },
      { en: "get sloppy",         ua: "набратися, перебрати",        note: "напитися до втрати координації" },
      { en: "boo",                ua: "кохана/коханий",              note: "ніжне звертання до партнера" },
      { en: "second best",        ua: "другосортний",                note: "гірший варіант, «запаска»; тут — «ти ніколи нею не була»" },
      { en: "fake it 'til you make it", ua: "вдавай, поки не вийде", note: "удавай упевненість/успіх, поки він не стане справжнім" },
      { en: "break it off",       ua: "порвати стосунки",            note: "розійтися, припинити стосунки" },
      { en: "faded",              ua: "напідпитку, у відключці",     note: "сильно п'яний або під кайфом" },
      { en: "chase your dreams",  ua: "гнатися за мрією",            note: "наполегливо домагатися своїх цілей" },
      { en: "hot",                ua: "сексуальна, приваблива",      note: "тут не «гаряча» буквально, а про привабливість" }
    ]
  }
  ,
  {
    id: "neffex-pro",
    artist: "NEFFEX",
    title: "Pro 👠",
    ytId: "FKcDtEtT3wU",
    sections: [
      { label: "ВСТУП", lines: [
        { en: "I wanna say some', yeah, let's go (I wanna say some', yeah, let's go)", ua: "Хочу дещо сказати, так, погнали (Хочу дещо сказати, так, погнали)" }
      ]},
      { label: "КУПЛЕТ 1", lines: [
        { en: "Yeah, I don't know where she came from (Where she came from)", ua: "Так, я не знаю, звідки вона взялася (Звідки вона взялася)" },
        { en: "But, God damn, I wanna say some' (I wanna say some')",         ua: "Але, чорт забирай, хочу дещо сказати (Хочу дещо сказати)" },
        { en: "She a dime, wanna make her mine (Make her mine)",             ua: "Вона — справжня красуня, хочу, щоб була моєю (Була моєю)" },
        { en: "Heard through the Grapevine, she a great time (Great time)",  ua: "Чув по чутках, що з нею весело (Весело)" },
        { en: "Yeah, it should be a God damn crime (Damn crime)",            ua: "Так, це мало б бути справжнім злочином (Злочином)" },
        { en: "To look that damn fine (Damn fine)",                          ua: "Виглядати так до біса гарно (До біса гарно)" },
        { en: "Gotta lock her up and throw away the key (Throw away the key)", ua: "Треба замкнути її й викинути ключ (Викинути ключ)" },
        { en: "Or you could lock her up and give the key to me (Give the key to me)", ua: "Або замкни її й віддай ключа мені (Віддай ключа мені)" },
        { en: "She likes to take it down low, down low",                     ua: "Вона любить опускатися низько, зовсім низько" },
        { en: "Drop it down to the ground floor, the ground floor",          ua: "Аж до самої підлоги, до самого низу" },
        { en: "I just wanna go and explore and explore",                     ua: "Я просто хочу досліджувати й досліджувати" },
        { en: "Oh, baby, I just want more, I want more",                     ua: "О, крихітко, я просто хочу більше, хочу більше" },
        { en: "Got a body like a rockstar, a rockstar",                      ua: "Тіло — як у рок-зірки, рок-зірки" },
        { en: "Yeah, that shit is lookin' rock hard, yeah, rock hard",       ua: "Так, виглядає міцно, аж твердо, так, твердо" },
        { en: "I would put her on the roster, the roster",                   ua: "Я б узяв її до складу, до своєї команди" },
        { en: "'Cause she keeps on gettin' hotter and hotter",               ua: "Бо вона стає все гарячішою й гарячішою" }
      ]},
      { label: "ПРИСПІВ", lines: [
        { en: "Ooh, baby, let's go, she doesn't take it slow (Yeah, it slow)", ua: "У-у, крихітко, погнали, вона не зволікає (Так, повільно)" },
        { en: "She's puttin' on a show, she's actin' like a pro (A show, a slow)", ua: "Вона влаштовує справжнє шоу, поводиться як профі (Шоу, повільно)" },
        { en: "Ooh, baby, let's go, she doesn't take it slow (Yeah, it slow)", ua: "У-у, крихітко, погнали, вона не зволікає (Так, повільно)" },
        { en: "She's puttin' on a show, she's actin' like a pro (A show, a slow)", ua: "Вона влаштовує справжнє шоу, поводиться як профі (Шоу, повільно)" },
        { en: "Ooh, baby, let's go",                                         ua: "У-у, крихітко, погнали" }
      ]},
      { label: "ПРОГРАШ", lines: [
        { en: "Ooh, baby, let's go",                                         ua: "У-у, крихітко, погнали" }
      ]},
      { label: "КУПЛЕТ 2", lines: [
        { en: "Ooh, she lookin' straight from the city (From the city)",     ua: "У-у, вона наче просто з великого міста (З міста)" },
        { en: "Oh, man, she lookin' so pretty (So pretty)",                  ua: "О, чуваку, вона така гарна (Така гарна)" },
        { en: "God damn, I'd like to get busy, yeah (Get busy)",             ua: "Чорт забирай, я б не проти зайнятися ділом, так (Зайнятися)" },
        { en: "So, baby girl, come with me (Come with me)",                  ua: "Тож, крихітко, ходи зі мною (Ходи зі мною)" },
        { en: "Yeah, we take it outside, oh (Outside, oh)",                  ua: "Так, виходимо назовні, о (Назовні, о)" },
        { en: "Yeah, wanna stay up all night, oh (All night, oh)",           ua: "Так, хочу не спати всю ніч, о (Усю ніч, о)" },
        { en: "Yeah, wanna get it all right, oh (All right, oh)",            ua: "Так, хочу, щоб усе вийшло як слід, о (Як слід, о)" },
        { en: "Yeah, now, she wanna slip and slide, oh",                     ua: "Так, тепер вона хоче ковзати й звиватися, о" },
        { en: "She got a fine-ass body with her head on straight",          ua: "У неї збіса гарне тіло й голова на плечах" },
        { en: "And she look a little naughty, but that's A-okay",            ua: "І вона трохи пустотлива, але це цілком окей" },
        { en: "Now, I wanna get a drink, just you and me",                   ua: "Тепер хочу випити, тільки ти і я" },
        { en: "I don't really wanna think, I just wanna be",                 ua: "Не дуже хочу думати, просто хочу бути" },
        { en: "She givin' third degree burns, man, I think I need a doctor", ua: "Вона пече так, що третій ступінь опіку, чуваку, мабуть, мені потрібен лікар" },
        { en: "Got me concerned 'cause she got me hot and bothered",         ua: "Я аж занепокоївся, бо вона мене розпалила й завела" },
        { en: "Everything she earned, didn't get it from her father",        ua: "Усе, що в неї є, вона здобула сама, не від батька" },
        { en: "Man, you think I'd learn, but she turns me to a monster",     ua: "Чуваку, думаєш, я навчуся, та вона перетворює мене на монстра" }
      ]},
      { label: "ПРИСПІВ", lines: [
        { en: "Ooh, baby, let's go, she doesn't take it slow (Yeah, it slow)", ua: "У-у, крихітко, погнали, вона не зволікає (Так, повільно)" },
        { en: "She's puttin' on a show, she's actin' like a pro (A show, a slow)", ua: "Вона влаштовує справжнє шоу, поводиться як профі (Шоу, повільно)" },
        { en: "Ooh, baby, let's go, she doesn't take it slow (Yeah, it slow)", ua: "У-у, крихітко, погнали, вона не зволікає (Так, повільно)" },
        { en: "She's puttin' on a show, she's actin' like a pro (A show, a slow)", ua: "Вона влаштовує справжнє шоу, поводиться як профі (Шоу, повільно)" },
        { en: "Ooh, baby, let's go",                                         ua: "У-у, крихітко, погнали" }
      ]},
      { label: "ПРОГРАШ", lines: [
        { en: "Ooh, baby, let's go",                                         ua: "У-у, крихітко, погнали" }
      ]}
    ],
    glossary: {
      "wanna": "хочу (want to)", "some'": "дещо (something)", "came": "прийшла (від come)",
      "god damn": "чорт забирай (вигук подиву/захоплення)", "damn": "до біса, клятий (підсилення)",
      "dime": "красуня на всі сто (dime — «десятка», ідеал)", "mine": "моя/моє",
      "heard": "чув (від hear)", "grapevine": "чутки (heard through the grapevine — дізнатися з чуток)",
      "crime": "злочин", "fine": "тут: гарний, привабливий", "gotta": "мусиш (got to)",
      "lock": "замкнути; lock up — замкнути, посадити", "throw": "кидати; throw away — викинути",
      "key": "ключ", "low": "низько", "drop": "опускати, скидати",
      "ground": "земля; ground floor — перший поверх, самий низ", "floor": "підлога; поверх",
      "explore": "досліджувати, вивчати", "more": "більше",
      "body": "тіло", "rockstar": "рок-зірка", "shit": "тут: «це все» (груб. підсилення)",
      "rock hard": "твердий як камінь", "roster": "склад команди, список гравців",
      "hotter": "гарячіша", "slow": "повільно; take it slow — не поспішати",
      "puttin'": "влаштовує (put on a show — влаштувати шоу)", "show": "шоу, видовище",
      "actin'": "поводиться, грає", "pro": "профі, професіонал (тут: майстриня своєї справи)",
      "straight": "прямо; straight from — прямісінько з; head on straight — з головою на плечах",
      "city": "місто (велике)", "pretty": "гарна, симпатична",
      "busy": "зайнятий; get busy — зайнятися ділом (тут: інтимний натяк)",
      "outside": "назовні, надворі", "stay up": "не спати, засидітися",
      "all right": "як слід, гаразд", "slip": "ковзати, прослизати", "slide": "ковзати, сповзати",
      "fine-ass": "збіса гарний (груб. підсилення)", "naughty": "пустотлива, грайливо-неслухняна",
      "a-okay": "цілком окей, повний порядок", "drink": "випивка; випити",
      "givin'": "дає; тут: «пече»", "third degree": "третій ступінь (найтяжчий опік)",
      "burns": "опіки", "doctor": "лікар", "concerned": "занепокоєний, стурбований",
      "hot and bothered": "розпалений і збуджений", "earned": "заробила, здобула",
      "father": "батько", "learn": "вчитися, навчатися", "turns": "перетворює (turn into)",
      "monster": "монстр, чудовисько", "outside,": "назовні"
    },
    slang: [
      { en: "say something",        ua: "сказати дещо (захоплено)",   note: "тут: «не можу мовчати, мушу висловитись» — від захвату" },
      { en: "dime",                 ua: "красуня на всі сто",         note: "«dime» = десятка з десяти; ідеальна дівчина" },
      { en: "heard through the grapevine", ua: "дізнатися з чуток",   note: "ідіома: почути неофіційно, пліткою" },
      { en: "lock her up, throw away the key", ua: "замкнути й викинути ключ", note: "гіпербола: «така, що хочеться нікому не віддавати»" },
      { en: "take it down low",     ua: "опускатися низько",          note: "про танець (присідати); з натяком" },
      { en: "rock hard",            ua: "твердий як камінь",          note: "про підтягнуте тіло; гра слів з rockstar" },
      { en: "put on the roster",    ua: "взяти до складу команди",    note: "спортивна метафора: «обрати її собі»" },
      { en: "take it slow",         ua: "не поспішати",               note: "тут навпаки — «вона НЕ зволікає»" },
      { en: "put on a show",        ua: "влаштувати шоу",             note: "ефектно показати себе, справити враження" },
      { en: "act like a pro",       ua: "поводитись як профі",        note: "«pro» = майстриня; з двозначним підтекстом (натяк)" },
      { en: "get busy",             ua: "зайнятися ділом",            note: "евфемізм інтиму (груб.-розм.)" },
      { en: "head on straight",     ua: "голова на плечах",           note: "розважлива, тямуща (have your head on straight)" },
      { en: "slip and slide",       ua: "ковзати й звиватися",        note: "натяк (від назви водної гірки)" },
      { en: "fine-ass",             ua: "збіса гарний",               note: "груба, але схвальна оцінка зовнішності" },
      { en: "A-okay",               ua: "повний порядок",             note: "усе чудово, жодних проблем" },
      { en: "third degree burns",   ua: "опіки третього ступеня",     note: "гіпербола: «вона така гаряча, що я обпікся»" },
      { en: "hot and bothered",     ua: "розпалений і збуджений",     note: "ідіома: схвильований і сексуально заведений" },
      { en: "turn into a monster",  ua: "перетворити на монстра",     note: "«вона пробуджує в мені звіра» — втрата контролю від пристрасті" }
    ]
  }
  ,
  {
    id: "neffex-self-made",
    artist: "NEFFEX",
    title: "Self Made 👔",
    ytId: "5fSYGKYDK5E",
    sections: [
      { label: "КУПЛЕТ 1", lines: [
        { en: "Growin' up in Cali, yeah, you know I love the weather",       ua: "Виростав у Каліфорнії, так, ти знаєш — я люблю тутешню погоду" },
        { en: "Limelight, hit 'em and you know I handle pressure",           ua: "У світлі софітів б'ю влучно — і ти знаєш, я витримую тиск" },
        { en: "I do what I want, so, I'm never sayin', \"Never\"",           ua: "Я роблю, що хочу, тож ніколи не кажу «ніколи»" },
        { en: "I get what I want, so, they call me, \"Go-getter,\" yeah",    ua: "Я отримую, що хочу, тож мене звуть «пробивним», так" },
        { en: "I know he does it good, but you know I do it better",         ua: "Я знаю, він робить добре, але ти знаєш — я роблю краще" },
        { en: "So misunderstood, if she want it, then I let her",            ua: "Такий незрозумілий для всіх; якщо вона хоче — я дозволяю" },
        { en: "Everybody knows if I want her, then I get her",               ua: "Усі знають: якщо я захочу її — я її отримаю" },
        { en: "She gave me that look, yeah, she know she thinks I'm clever (Yeah)", ua: "Вона глянула на мене тим поглядом, так, вона знає, що вважає мене розумником (Так)" }
      ]},
      { label: "ПРИСПІВ", lines: [
        { en: "I don't think I do it good, no, I think I do it great (Hoo)", ua: "Я не думаю, що роблю це добре — ні, я думаю, що роблю це чудово (Гу)" },
        { en: "They would do it if they could, they can't do it, so, they hate", ua: "Вони б зробили, якби могли; не можуть — тому ненавидять" },
        { en: "Everybody wanna look, but nobody wanna play (Hoo)",           ua: "Усі хочуть дивитися, та ніхто не хоче грати (Гу)" },
        { en: "Stealing eyes like a crook, while I put it in display",       ua: "Краду погляди, наче злодій, поки я виставляю все напоказ" },
        { en: "I don't do it by the book, no, I do my own thing (Hoo)",      ua: "Я роблю це не за правилами — ні, я роблю по-своєму (Гу)" },
        { en: "That's why every single hook got 'em singin' like me",        ua: "Ось чому кожен мій приспів змушує їх співати, як я" },
        { en: "And I ain't in any rush 'cause I'm finally gettin' paid (Hoo)", ua: "І я нікуди не поспішаю, бо нарешті почав заробляти (Гу)" },
        { en: "Don't believe in any luck, I believe I'm self made, yeah",    ua: "Не вірю в жодну удачу — вірю, що я зробив себе сам, так" }
      ]},
      { label: "ПРОГРАШ", lines: [
        { en: "(Hoo, woah, woah, woah)",                                     ua: "(Гу, воа, воа, воа)" },
        { en: "Don't believe in any luck (Hoo)",                            ua: "Не вірю в жодну удачу (Гу)" },
        { en: "I believe I'm self made, yeah (Woah, woah)",                 ua: "Вірю, що я зробив себе сам, так (Воа, воа)" },
        { en: "Yeah, let's go (Hoo, woah, woah)",                           ua: "Так, погнали (Гу, воа, воа)" }
      ]},
      { label: "КУПЛЕТ 2", lines: [
        { en: "Catch me at the top, sippin' shots of Patrón",               ua: "Застанеш мене на вершині, потягуючи шоти Patrón" },
        { en: "I will never stop 'til the road is my home",                 ua: "Я ніколи не спинюсь, поки дорога не стане моїм домом" },
        { en: "I'm about to pop, everybody's gonna know",                   ua: "Я ось-ось вистрелю, і всі про це дізнаються" },
        { en: "When the beat drops, they be yelling, \"B-Ho\"",             ua: "Коли вривається біт, вони кричать «B-Ho»" },
        { en: "Girls in crop-tops, drop tops at our shows",                 ua: "Дівчата в коротких топах, кабріолети з відкритим дахом на наших шоу" },
        { en: "Miniskirts rock, got us all like, \"Woah\"",                 ua: "Міні-спідниці — це вогонь, від них ми всі такі: «Воа»" },
        { en: "All the pretty ladies lined up, front row",                  ua: "Усі красуні вишикувались у першому ряду" },
        { en: "Driving me crazy, I just wanna take 'em home",               ua: "Зводять мене з розуму, я просто хочу забрати їх додому" },
        { en: "Got it on lock, yeah, you could call me, \"Pro\"",           ua: "Усе під контролем, так, можеш звати мене «профі»" },
        { en: "Parties on the block, make sure the girls know",             ua: "Вечірки на районі — подбай, щоб дівчата були в курсі" },
        { en: "Now, it's gettin' hot up in here, oh, no",                   ua: "Тепер тут стає гаряче, о, ні" },
        { en: "Think Nelly had it right, better take off all your clothes", ua: "Гадаю, Неллі мав рацію — краще скинь увесь одяг" },
        { en: "Future's lookin' bright, now, I'm finally in the zone",       ua: "Майбутнє світле, тепер я нарешті в ударі" },
        { en: "Three years of my life, I committed to the growth",          ua: "Три роки життя я присвятив зростанню" },
        { en: "Soldier Boy tell 'em, number one ringtone",                 ua: "Як Soulja Boy казав — рінгтон номер один" },
        { en: "I'm the reason people texting",                             ua: "Це через мене люди пишуть повідомлення" },
        { en: "'Cause they blowin' up your phone (Yeah, yeah)",            ua: "Бо твій телефон розривається від дзвінків (Так, так)" }
      ]},
      { label: "ПРИСПІВ", lines: [
        { en: "I don't think I do it good, no, I think I do it great (Hoo)", ua: "Я не думаю, що роблю це добре — ні, я думаю, що роблю це чудово (Гу)" },
        { en: "They would do it if they could, they can't do it, so, they hate", ua: "Вони б зробили, якби могли; не можуть — тому ненавидять" },
        { en: "Everybody wanna look, but nobody wanna play (Hoo)",           ua: "Усі хочуть дивитися, та ніхто не хоче грати (Гу)" },
        { en: "Stealing eyes like a crook, while I put it in display",       ua: "Краду погляди, наче злодій, поки я виставляю все напоказ" },
        { en: "I don't do it by the book, no, I do my own thing (Hoo)",      ua: "Я роблю це не за правилами — ні, я роблю по-своєму (Гу)" },
        { en: "That's why every single hook got 'em singin' like me",        ua: "Ось чому кожен мій приспів змушує їх співати, як я" },
        { en: "And I ain't in any rush 'cause I'm finally gettin' paid (Hoo)", ua: "І я нікуди не поспішаю, бо нарешті почав заробляти (Гу)" },
        { en: "Don't believe in any luck, I believe I'm self made, yeah",    ua: "Не вірю в жодну удачу — вірю, що я зробив себе сам, так" }
      ]},
      { label: "ПРОГРАШ", lines: [
        { en: "(Hoo, woah, woah, woah)",                                     ua: "(Гу, воа, воа, воа)" },
        { en: "Don't believe in any luck (Hoo)",                            ua: "Не вірю в жодну удачу (Гу)" },
        { en: "I believe I'm self made, yeah (Woah, woah)",                 ua: "Вірю, що я зробив себе сам, так (Воа, воа)" }
      ]}
    ],
    glossary: {
      "growin'": "виростаю (grow up — рости, дорослішати)", "cali": "Каліфорнія (розм. Cali)",
      "weather": "погода", "limelight": "світло рампи, центр уваги, слава",
      "hit": "вдарити; hit 'em — влучати, вражати", "'em": "їх / їм (them)",
      "handle": "давати раду, справлятися", "pressure": "тиск, напруга",
      "go-getter": "пробивна людина, хват", "misunderstood": "незрозумілий (для інших)",
      "let": "дозволяти", "look": "погляд", "clever": "розумний, кмітливий",
      "great": "чудовий, прекрасний", "could": "міг би", "hate": "ненавидіти",
      "nobody": "ніхто", "play": "грати, бавитися", "stealing": "краду (steal — красти)",
      "eyes": "очі; steal eyes — притягувати погляди", "crook": "шахрай, злодій",
      "display": "показ; put on display — виставляти напоказ", "book": "книга; by the book — за правилами",
      "own thing": "своя справа; do my own thing — робити по-своєму",
      "single": "кожен; every single — геть кожен", "hook": "приспів, чіпкий мотив пісні",
      "singin'": "співають", "rush": "поспіх; in a rush — поспішати", "finally": "нарешті",
      "paid": "оплачений; gettin' paid — заробляти", "believe": "вірити",
      "luck": "удача, везіння", "self made": "той, хто всього досяг сам",
      "woah": "воа (вигук подиву)", "catch": "застати, спіймати", "top": "вершина, верхівка",
      "sippin'": "потягую (пити дрібними ковтками)", "shots": "шоти (порції міцного)",
      "patrón": "Patrón (марка преміум-текіли)", "'til": "поки не (until)",
      "road": "дорога", "home": "дім", "pop": "вистрелити, «бахнути» (стати популярним)",
      "gonna": "збираюся (going to)", "beat": "біт, ритм", "drops": "вривається (beat drop — вибух біту)",
      "yelling": "кричать", "crop-tops": "короткі топи (відкривають живіт)",
      "drop tops": "кабріолети (авто з відкидним дахом)", "shows": "концерти, шоу",
      "miniskirts": "міні-спідниці", "rock": "тут: «це вогонь, круто»", "pretty": "гарні, симпатичні",
      "ladies": "леді, дівчата", "lined up": "вишикувались (line up — ставати в чергу)",
      "front row": "перший ряд", "crazy": "божевільний; drive crazy — зводити з розуму",
      "lock": "замок; on lock — під повним контролем", "pro": "профі, майстер",
      "parties": "вечірки", "block": "квартал, район", "make sure": "подбати, переконатися",
      "hot": "гаряче", "nelly": "Nelly (репер; хіт «Hot in Herre»)", "clothes": "одяг",
      "future": "майбутнє", "bright": "світлий, яскравий", "zone": "in the zone — у потоці, в ударі",
      "committed": "присвятив, віддався (commit — зобов'язатися)", "growth": "зростання, розвиток",
      "ringtone": "рінгтон, мелодія дзвінка", "reason": "причина", "texting": "пишуть повідомлення",
      "blowin' up": "розривається (про телефон — безперервні дзвінки/повідомлення)", "phone": "телефон"
    },
    slang: [
      { en: "self made",          ua: "зробив себе сам",            note: "досяг усього власними силами, без чужої допомоги" },
      { en: "limelight",          ua: "центр уваги, слава",         note: "буквально «світло рампи» — бути на видноті" },
      { en: "go-getter",          ua: "пробивний, хват",            note: "цілеспрямована, наполеглива людина" },
      { en: "do it by the book",  ua: "робити за правилами",        note: "діяти строго за інструкцією; тут — навпаки" },
      { en: "do my own thing",    ua: "робити по-своєму",           note: "жити/творити за власними правилами" },
      { en: "hook",               ua: "приспів, чіпкий мотив",      note: "найзапам'ятовуваніша частина пісні" },
      { en: "gettin' paid",       ua: "заробляти",                  note: "нарешті отримувати гроші за свою справу" },
      { en: "steal eyes",         ua: "притягувати погляди",        note: "бути в центрі уваги, привертати очі" },
      { en: "shots of Patrón",    ua: "шоти текіли Patrón",         note: "Patrón — преміум-марка текіли; shot — порція міцного" },
      { en: "about to pop",       ua: "ось-ось вистрелю",           note: "от-от стану популярним, «вибухну»" },
      { en: "beat drops",         ua: "вривається біт",             note: "момент вибуху ритму в треку, кульмінація" },
      { en: "drop tops",          ua: "кабріолети",                 note: "авто з відкидним дахом (drop-top)" },
      { en: "rock",               ua: "це вогонь, круто",           note: "«miniskirts rock» — міні-спідниці неперевершені" },
      { en: "on lock",            ua: "під контролем",              note: "повністю схоплено, «все в руках»" },
      { en: "Nelly reference",    ua: "відсилання до Nelly",        note: "хіт «Hot in Herre»: «it's getting hot… take off all your clothes»" },
      { en: "in the zone",        ua: "у потоці, в ударі",          note: "стан максимальної зосередженості й продуктивності" },
      { en: "Soulja Boy",         ua: "Soulja Boy (репер)",         note: "«Soldier Boy» — натяк на репера; «Crank That» довго був хіт-рінгтоном" },
      { en: "blow up your phone", ua: "телефон розривається",       note: "безперервні дзвінки/повідомлення" }
    ]
  }
];

if (typeof window !== "undefined") { window.SONGS = SONGS; }
